/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq;


import cn.zyj.dbexporter.jooq.tables.AssetsDevice;
import cn.zyj.dbexporter.jooq.tables.AssetsOperate;
import cn.zyj.dbexporter.jooq.tables.AssetsReceiver;
import cn.zyj.dbexporter.jooq.tables.DjangoMigrations;
import cn.zyj.dbexporter.jooq.tables.SmsBlacklist;
import cn.zyj.dbexporter.jooq.tables.SmsWhitelist;
import cn.zyj.dbexporter.jooq.tables.TAccessControlLog;
import cn.zyj.dbexporter.jooq.tables.TAlipayDataUploadlog;
import cn.zyj.dbexporter.jooq.tables.TAnnualReview;
import cn.zyj.dbexporter.jooq.tables.TAssetsDevice;
import cn.zyj.dbexporter.jooq.tables.TAssetsDeviceBelong;
import cn.zyj.dbexporter.jooq.tables.TAssetsDeviceBelongCopy;
import cn.zyj.dbexporter.jooq.tables.TAssetsDeviceHistory;
import cn.zyj.dbexporter.jooq.tables.TAssetsDevicePackage;
import cn.zyj.dbexporter.jooq.tables.TAssetsPackages;
import cn.zyj.dbexporter.jooq.tables.TAutoCutMoneyQueue;
import cn.zyj.dbexporter.jooq.tables.TBankRechargeList;
import cn.zyj.dbexporter.jooq.tables.TBcity;
import cn.zyj.dbexporter.jooq.tables.TBillCalculateFlag;
import cn.zyj.dbexporter.jooq.tables.TBillCheck;
import cn.zyj.dbexporter.jooq.tables.TBillCheckStart;
import cn.zyj.dbexporter.jooq.tables.TBillCrm;
import cn.zyj.dbexporter.jooq.tables.TBillOverdueSmsRecords;
import cn.zyj.dbexporter.jooq.tables.TCarts;
import cn.zyj.dbexporter.jooq.tables.TCartsHistory;
import cn.zyj.dbexporter.jooq.tables.TCartsLogs;
import cn.zyj.dbexporter.jooq.tables.TCouponCustomerList;
import cn.zyj.dbexporter.jooq.tables.TCouponList;
import cn.zyj.dbexporter.jooq.tables.TCrmOrderErrorLog;
import cn.zyj.dbexporter.jooq.tables.TCronLog;
import cn.zyj.dbexporter.jooq.tables.TCustomer;
import cn.zyj.dbexporter.jooq.tables.TCustomerAccount;
import cn.zyj.dbexporter.jooq.tables.TCustomerActionLogs;
import cn.zyj.dbexporter.jooq.tables.TCustomerActionLogsBak;
import cn.zyj.dbexporter.jooq.tables.TCustomerAddress;
import cn.zyj.dbexporter.jooq.tables.TCustomerAlipayCreditResult;
import cn.zyj.dbexporter.jooq.tables.TCustomerAlipayMall;
import cn.zyj.dbexporter.jooq.tables.TCustomerAlipayOrderNoLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerBalanceDateLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerBill;
import cn.zyj.dbexporter.jooq.tables.TCustomerBillMonth;
import cn.zyj.dbexporter.jooq.tables.TCustomerBillMonthProof;
import cn.zyj.dbexporter.jooq.tables.TCustomerBlack;
import cn.zyj.dbexporter.jooq.tables.TCustomerCoupon;
import cn.zyj.dbexporter.jooq.tables.TCustomerCreditBalanceEvent;
import cn.zyj.dbexporter.jooq.tables.TCustomerCrmPaytypeBandLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerHint;
import cn.zyj.dbexporter.jooq.tables.TCustomerInvoiceBasedBill;
import cn.zyj.dbexporter.jooq.tables.TCustomerLoginLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerMemberInvite;
import cn.zyj.dbexporter.jooq.tables.TCustomerNotice;
import cn.zyj.dbexporter.jooq.tables.TCustomerPasswdChangeLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerPhoneChangeLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerProductLimit;
import cn.zyj.dbexporter.jooq.tables.TCustomerRemarkLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerSay;
import cn.zyj.dbexporter.jooq.tables.TCustomerSmsCode;
import cn.zyj.dbexporter.jooq.tables.TCustomerSmsCodeCopy;
import cn.zyj.dbexporter.jooq.tables.TCustomerStatusLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerSummitInfo;
import cn.zyj.dbexporter.jooq.tables.TCustomerToSaasLog;
import cn.zyj.dbexporter.jooq.tables.TCustomerWechat;
import cn.zyj.dbexporter.jooq.tables.TCustomerWithdraw;
import cn.zyj.dbexporter.jooq.tables.TCutMoneyDay;
import cn.zyj.dbexporter.jooq.tables.TCutbillDepositOrder;
import cn.zyj.dbexporter.jooq.tables.TDeviceAllocate;
import cn.zyj.dbexporter.jooq.tables.TDynamicCustomerCutMoneyDateLog;
import cn.zyj.dbexporter.jooq.tables.TEquipmentEvent;
import cn.zyj.dbexporter.jooq.tables.TEquipmentTransLog;
import cn.zyj.dbexporter.jooq.tables.TErpSku;
import cn.zyj.dbexporter.jooq.tables.TErpSpu;
import cn.zyj.dbexporter.jooq.tables.TEveryDay;
import cn.zyj.dbexporter.jooq.tables.TFixPaydateLog;
import cn.zyj.dbexporter.jooq.tables.TFrozenMoneyDeposit;
import cn.zyj.dbexporter.jooq.tables.TGroupAccount;
import cn.zyj.dbexporter.jooq.tables.TGroupAccountRela;
import cn.zyj.dbexporter.jooq.tables.TGroupAccounts;
import cn.zyj.dbexporter.jooq.tables.TGroupApply;
import cn.zyj.dbexporter.jooq.tables.TGroupChildFunctionStatus;
import cn.zyj.dbexporter.jooq.tables.TGroupChildOrderVerify;
import cn.zyj.dbexporter.jooq.tables.TGroupCustomerOperLog;
import cn.zyj.dbexporter.jooq.tables.TGroupPermission;
import cn.zyj.dbexporter.jooq.tables.TGroupPermissionRela;
import cn.zyj.dbexporter.jooq.tables.TGroups;
import cn.zyj.dbexporter.jooq.tables.THelpCustomerOrderLog;
import cn.zyj.dbexporter.jooq.tables.THelpCustomerOrderLogDetail;
import cn.zyj.dbexporter.jooq.tables.THomeFloor;
import cn.zyj.dbexporter.jooq.tables.THomeProduct;
import cn.zyj.dbexporter.jooq.tables.TIndexFloor;
import cn.zyj.dbexporter.jooq.tables.TIndexFloorCopy;
import cn.zyj.dbexporter.jooq.tables.TIndexProduct;
import cn.zyj.dbexporter.jooq.tables.TIndexProductCopy;
import cn.zyj.dbexporter.jooq.tables.TInvoiceDetail;
import cn.zyj.dbexporter.jooq.tables.TInvoiceNotice;
import cn.zyj.dbexporter.jooq.tables.TInvoiceRequest;
import cn.zyj.dbexporter.jooq.tables.TInvoiceRequestEvent;
import cn.zyj.dbexporter.jooq.tables.TInvoiceRequestOverLog;
import cn.zyj.dbexporter.jooq.tables.TLoopLogo;
import cn.zyj.dbexporter.jooq.tables.TMacBindLog;
import cn.zyj.dbexporter.jooq.tables.TMacDevice;
import cn.zyj.dbexporter.jooq.tables.TMacLog;
import cn.zyj.dbexporter.jooq.tables.TManager;
import cn.zyj.dbexporter.jooq.tables.TManagerFile;
import cn.zyj.dbexporter.jooq.tables.TManagerLog;
import cn.zyj.dbexporter.jooq.tables.TMenu;
import cn.zyj.dbexporter.jooq.tables.TMessageNotice;
import cn.zyj.dbexporter.jooq.tables.TNetRechargeList;
import cn.zyj.dbexporter.jooq.tables.TNetRechargeRequest;
import cn.zyj.dbexporter.jooq.tables.TNewsCategory;
import cn.zyj.dbexporter.jooq.tables.TNewsContent;
import cn.zyj.dbexporter.jooq.tables.TOfferGoods;
import cn.zyj.dbexporter.jooq.tables.TOpLogs;
import cn.zyj.dbexporter.jooq.tables.TOrderBalance;
import cn.zyj.dbexporter.jooq.tables.TOrderBill;
import cn.zyj.dbexporter.jooq.tables.TOrderBillChangeLog;
import cn.zyj.dbexporter.jooq.tables.TOrderBillConfirm;
import cn.zyj.dbexporter.jooq.tables.TOrderBillCutMoneyDateLog;
import cn.zyj.dbexporter.jooq.tables.TOrderBillDetail;
import cn.zyj.dbexporter.jooq.tables.TOrderChangeRent;
import cn.zyj.dbexporter.jooq.tables.TOrderChangeStartRentLog;
import cn.zyj.dbexporter.jooq.tables.TOrderCount;
import cn.zyj.dbexporter.jooq.tables.TOrderCoupon;
import cn.zyj.dbexporter.jooq.tables.TOrderCreateFail;
import cn.zyj.dbexporter.jooq.tables.TOrderEvent;
import cn.zyj.dbexporter.jooq.tables.TOrderExchange;
import cn.zyj.dbexporter.jooq.tables.TOrderExpress;
import cn.zyj.dbexporter.jooq.tables.TOrderItems;
import cn.zyj.dbexporter.jooq.tables.TOrderItemsDetail;
import cn.zyj.dbexporter.jooq.tables.TOrderItemsDetailLog;
import cn.zyj.dbexporter.jooq.tables.TOrderItemsDetailReturnLog;
import cn.zyj.dbexporter.jooq.tables.TOrderNews;
import cn.zyj.dbexporter.jooq.tables.TOrderPayEvent;
import cn.zyj.dbexporter.jooq.tables.TOrderPayableBill;
import cn.zyj.dbexporter.jooq.tables.TOrderProductSku;
import cn.zyj.dbexporter.jooq.tables.TOrderQueue;
import cn.zyj.dbexporter.jooq.tables.TOrderRefund;
import cn.zyj.dbexporter.jooq.tables.TOrderRenewLog;
import cn.zyj.dbexporter.jooq.tables.TOrderRentTypeChangeLog;
import cn.zyj.dbexporter.jooq.tables.TOrderRepay;
import cn.zyj.dbexporter.jooq.tables.TOrderSearch;
import cn.zyj.dbexporter.jooq.tables.TOrderShare;
import cn.zyj.dbexporter.jooq.tables.TOrderTransLog;
import cn.zyj.dbexporter.jooq.tables.TOrders;
import cn.zyj.dbexporter.jooq.tables.TOverdueCustomer;
import cn.zyj.dbexporter.jooq.tables.TPhoneTemp;
import cn.zyj.dbexporter.jooq.tables.TPicPatchList;
import cn.zyj.dbexporter.jooq.tables.TPriceCalc;
import cn.zyj.dbexporter.jooq.tables.TProductAssemble;
import cn.zyj.dbexporter.jooq.tables.TProductAssembleCopy;
import cn.zyj.dbexporter.jooq.tables.TProductBrand;
import cn.zyj.dbexporter.jooq.tables.TProductCategory;
import cn.zyj.dbexporter.jooq.tables.TProductCategoryClassificationAttr;
import cn.zyj.dbexporter.jooq.tables.TProductChange;
import cn.zyj.dbexporter.jooq.tables.TProductCheck;
import cn.zyj.dbexporter.jooq.tables.TProductDescribeList;
import cn.zyj.dbexporter.jooq.tables.TProductGhost;
import cn.zyj.dbexporter.jooq.tables.TProductImage;
import cn.zyj.dbexporter.jooq.tables.TProductKey;
import cn.zyj.dbexporter.jooq.tables.TProductLisCopy;
import cn.zyj.dbexporter.jooq.tables.TProductLis_01;
import cn.zyj.dbexporter.jooq.tables.TProductList;
import cn.zyj.dbexporter.jooq.tables.TProductMajorOtherParam;
import cn.zyj.dbexporter.jooq.tables.TProductMajorParam;
import cn.zyj.dbexporter.jooq.tables.TProductQa;
import cn.zyj.dbexporter.jooq.tables.TProductRelet;
import cn.zyj.dbexporter.jooq.tables.TProductRentType;
import cn.zyj.dbexporter.jooq.tables.TProductRentTypeDetail;
import cn.zyj.dbexporter.jooq.tables.TProductSkuidInfo;
import cn.zyj.dbexporter.jooq.tables.TProductStatus;
import cn.zyj.dbexporter.jooq.tables.TProductStockNoticeQueue;
import cn.zyj.dbexporter.jooq.tables.TProductStockQueue;
import cn.zyj.dbexporter.jooq.tables.TProvince;
import cn.zyj.dbexporter.jooq.tables.TQuartzMonitor;
import cn.zyj.dbexporter.jooq.tables.TQuery;
import cn.zyj.dbexporter.jooq.tables.TRecycleApply;
import cn.zyj.dbexporter.jooq.tables.TRecycleOptions;
import cn.zyj.dbexporter.jooq.tables.TReleaseFrozenBalance;
import cn.zyj.dbexporter.jooq.tables.TRight;
import cn.zyj.dbexporter.jooq.tables.TRiskCustomerInfo;
import cn.zyj.dbexporter.jooq.tables.TRiskTelId;
import cn.zyj.dbexporter.jooq.tables.TRole;
import cn.zyj.dbexporter.jooq.tables.TRoleRight;
import cn.zyj.dbexporter.jooq.tables.TScity;
import cn.zyj.dbexporter.jooq.tables.TShipmentNotice;
import cn.zyj.dbexporter.jooq.tables.TShortcutMenu;
import cn.zyj.dbexporter.jooq.tables.TSmsBlacklistLog;
import cn.zyj.dbexporter.jooq.tables.TSmsFilter;
import cn.zyj.dbexporter.jooq.tables.TSmsLog;
import cn.zyj.dbexporter.jooq.tables.TSmsTemplate;
import cn.zyj.dbexporter.jooq.tables.TSmsTemplateBak;
import cn.zyj.dbexporter.jooq.tables.TSmsUploadLog;
import cn.zyj.dbexporter.jooq.tables.TStatDailyDevices;
import cn.zyj.dbexporter.jooq.tables.TStatDailyEquipment;
import cn.zyj.dbexporter.jooq.tables.TStatDailyOrders;
import cn.zyj.dbexporter.jooq.tables.TStatDailyUsers;
import cn.zyj.dbexporter.jooq.tables.TTestUser;
import cn.zyj.dbexporter.jooq.tables.TVatProfile;
import cn.zyj.dbexporter.jooq.tables.TWasteRequest;
import cn.zyj.dbexporter.jooq.tables.TWithdrawRequestEvent;
import cn.zyj.dbexporter.jooq.tables.TWxCustomer;
import cn.zyj.dbexporter.jooq.tables.Tickets;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbMall extends SchemaImpl {

    private static final long serialVersionUID = -1975103657;

    /**
     * The reference instance of <code>db_mall</code>
     */
    public static final DbMall DB_MALL = new DbMall();

    /**
     * The table <code>db_mall.assets_device</code>.
     */
    public final AssetsDevice ASSETS_DEVICE = cn.zyj.dbexporter.jooq.tables.AssetsDevice.ASSETS_DEVICE;

    /**
     * The table <code>db_mall.assets_operate</code>.
     */
    public final AssetsOperate ASSETS_OPERATE = cn.zyj.dbexporter.jooq.tables.AssetsOperate.ASSETS_OPERATE;

    /**
     * The table <code>db_mall.assets_receiver</code>.
     */
    public final AssetsReceiver ASSETS_RECEIVER = cn.zyj.dbexporter.jooq.tables.AssetsReceiver.ASSETS_RECEIVER;

    /**
     * The table <code>db_mall.django_migrations</code>.
     */
    public final DjangoMigrations DJANGO_MIGRATIONS = cn.zyj.dbexporter.jooq.tables.DjangoMigrations.DJANGO_MIGRATIONS;

    /**
     * The table <code>db_mall.sms_blacklist</code>.
     */
    public final SmsBlacklist SMS_BLACKLIST = cn.zyj.dbexporter.jooq.tables.SmsBlacklist.SMS_BLACKLIST;

    /**
     * The table <code>db_mall.sms_whitelist</code>.
     */
    public final SmsWhitelist SMS_WHITELIST = cn.zyj.dbexporter.jooq.tables.SmsWhitelist.SMS_WHITELIST;

    /**
     * The table <code>db_mall.tickets</code>.
     */
    public final Tickets TICKETS = cn.zyj.dbexporter.jooq.tables.Tickets.TICKETS;

    /**
     * The table <code>db_mall.t_access_control_log</code>.
     */
    public final TAccessControlLog T_ACCESS_CONTROL_LOG = cn.zyj.dbexporter.jooq.tables.TAccessControlLog.T_ACCESS_CONTROL_LOG;

    /**
     * 支付宝回传数据日志记录
     */
    public final TAlipayDataUploadlog T_ALIPAY_DATA_UPLOADLOG = cn.zyj.dbexporter.jooq.tables.TAlipayDataUploadlog.T_ALIPAY_DATA_UPLOADLOG;

    /**
     * 易点租2017年度数据查询记录
     */
    public final TAnnualReview T_ANNUAL_REVIEW = cn.zyj.dbexporter.jooq.tables.TAnnualReview.T_ANNUAL_REVIEW;

    /**
     * The table <code>db_mall.t_assets_device</code>.
     */
    public final TAssetsDevice T_ASSETS_DEVICE = cn.zyj.dbexporter.jooq.tables.TAssetsDevice.T_ASSETS_DEVICE;

    /**
     * The table <code>db_mall.t_assets_device_belong</code>.
     */
    public final TAssetsDeviceBelong T_ASSETS_DEVICE_BELONG = cn.zyj.dbexporter.jooq.tables.TAssetsDeviceBelong.T_ASSETS_DEVICE_BELONG;

    /**
     * The table <code>db_mall.t_assets_device_belong_copy</code>.
     */
    public final TAssetsDeviceBelongCopy T_ASSETS_DEVICE_BELONG_COPY = cn.zyj.dbexporter.jooq.tables.TAssetsDeviceBelongCopy.T_ASSETS_DEVICE_BELONG_COPY;

    /**
     * The table <code>db_mall.t_assets_device_history</code>.
     */
    public final TAssetsDeviceHistory T_ASSETS_DEVICE_HISTORY = cn.zyj.dbexporter.jooq.tables.TAssetsDeviceHistory.T_ASSETS_DEVICE_HISTORY;

    /**
     * The table <code>db_mall.t_assets_device_package</code>.
     */
    public final TAssetsDevicePackage T_ASSETS_DEVICE_PACKAGE = cn.zyj.dbexporter.jooq.tables.TAssetsDevicePackage.T_ASSETS_DEVICE_PACKAGE;

    /**
     * The table <code>db_mall.t_assets_packages</code>.
     */
    public final TAssetsPackages T_ASSETS_PACKAGES = cn.zyj.dbexporter.jooq.tables.TAssetsPackages.T_ASSETS_PACKAGES;

    /**
     * The table <code>db_mall.t_auto_cut_money_queue</code>.
     */
    public final TAutoCutMoneyQueue T_AUTO_CUT_MONEY_QUEUE = cn.zyj.dbexporter.jooq.tables.TAutoCutMoneyQueue.T_AUTO_CUT_MONEY_QUEUE;

    /**
     * The table <code>db_mall.t_bank_recharge_list</code>.
     */
    public final TBankRechargeList T_BANK_RECHARGE_LIST = cn.zyj.dbexporter.jooq.tables.TBankRechargeList.T_BANK_RECHARGE_LIST;

    /**
     * The table <code>db_mall.t_bcity</code>.
     */
    public final TBcity T_BCITY = cn.zyj.dbexporter.jooq.tables.TBcity.T_BCITY;

    /**
     * The table <code>db_mall.t_bill_calculate_flag</code>.
     */
    public final TBillCalculateFlag T_BILL_CALCULATE_FLAG = cn.zyj.dbexporter.jooq.tables.TBillCalculateFlag.T_BILL_CALCULATE_FLAG;

    /**
     * The table <code>db_mall.t_bill_check</code>.
     */
    public final TBillCheck T_BILL_CHECK = cn.zyj.dbexporter.jooq.tables.TBillCheck.T_BILL_CHECK;

    /**
     * The table <code>db_mall.t_bill_check_start</code>.
     */
    public final TBillCheckStart T_BILL_CHECK_START = cn.zyj.dbexporter.jooq.tables.TBillCheckStart.T_BILL_CHECK_START;

    /**
     * The table <code>db_mall.t_bill_crm</code>.
     */
    public final TBillCrm T_BILL_CRM = cn.zyj.dbexporter.jooq.tables.TBillCrm.T_BILL_CRM;

    /**
     * The table <code>db_mall.t_bill_overdue_sms_records</code>.
     */
    public final TBillOverdueSmsRecords T_BILL_OVERDUE_SMS_RECORDS = cn.zyj.dbexporter.jooq.tables.TBillOverdueSmsRecords.T_BILL_OVERDUE_SMS_RECORDS;

    /**
     * The table <code>db_mall.t_carts</code>.
     */
    public final TCarts T_CARTS = cn.zyj.dbexporter.jooq.tables.TCarts.T_CARTS;

    /**
     * The table <code>db_mall.t_carts_history</code>.
     */
    public final TCartsHistory T_CARTS_HISTORY = cn.zyj.dbexporter.jooq.tables.TCartsHistory.T_CARTS_HISTORY;

    /**
     * The table <code>db_mall.t_carts_logs</code>.
     */
    public final TCartsLogs T_CARTS_LOGS = cn.zyj.dbexporter.jooq.tables.TCartsLogs.T_CARTS_LOGS;

    /**
     * The table <code>db_mall.t_coupon_customer_list</code>.
     */
    public final TCouponCustomerList T_COUPON_CUSTOMER_LIST = cn.zyj.dbexporter.jooq.tables.TCouponCustomerList.T_COUPON_CUSTOMER_LIST;

    /**
     * The table <code>db_mall.t_coupon_list</code>.
     */
    public final TCouponList T_COUPON_LIST = cn.zyj.dbexporter.jooq.tables.TCouponList.T_COUPON_LIST;

    /**
     * The table <code>db_mall.t_crm_order_error_log</code>.
     */
    public final TCrmOrderErrorLog T_CRM_ORDER_ERROR_LOG = cn.zyj.dbexporter.jooq.tables.TCrmOrderErrorLog.T_CRM_ORDER_ERROR_LOG;

    /**
     * The table <code>db_mall.t_cron_log</code>.
     */
    public final TCronLog T_CRON_LOG = cn.zyj.dbexporter.jooq.tables.TCronLog.T_CRON_LOG;

    /**
     * The table <code>db_mall.t_customer</code>.
     */
    public final TCustomer T_CUSTOMER = cn.zyj.dbexporter.jooq.tables.TCustomer.T_CUSTOMER;

    /**
     * The table <code>db_mall.t_customer_account</code>.
     */
    public final TCustomerAccount T_CUSTOMER_ACCOUNT = cn.zyj.dbexporter.jooq.tables.TCustomerAccount.T_CUSTOMER_ACCOUNT;

    /**
     * The table <code>db_mall.t_customer_action_logs</code>.
     */
    public final TCustomerActionLogs T_CUSTOMER_ACTION_LOGS = cn.zyj.dbexporter.jooq.tables.TCustomerActionLogs.T_CUSTOMER_ACTION_LOGS;

    /**
     * The table <code>db_mall.t_customer_action_logs_bak</code>.
     */
    public final TCustomerActionLogsBak T_CUSTOMER_ACTION_LOGS_BAK = cn.zyj.dbexporter.jooq.tables.TCustomerActionLogsBak.T_CUSTOMER_ACTION_LOGS_BAK;

    /**
     * The table <code>db_mall.t_customer_address</code>.
     */
    public final TCustomerAddress T_CUSTOMER_ADDRESS = cn.zyj.dbexporter.jooq.tables.TCustomerAddress.T_CUSTOMER_ADDRESS;

    /**
     * The table <code>db_mall.t_customer_alipay_credit_result</code>.
     */
    public final TCustomerAlipayCreditResult T_CUSTOMER_ALIPAY_CREDIT_RESULT = cn.zyj.dbexporter.jooq.tables.TCustomerAlipayCreditResult.T_CUSTOMER_ALIPAY_CREDIT_RESULT;

    /**
     * The table <code>db_mall.t_customer_alipay_mall</code>.
     */
    public final TCustomerAlipayMall T_CUSTOMER_ALIPAY_MALL = cn.zyj.dbexporter.jooq.tables.TCustomerAlipayMall.T_CUSTOMER_ALIPAY_MALL;

    /**
     * The table <code>db_mall.t_customer_alipay_order_no_log</code>.
     */
    public final TCustomerAlipayOrderNoLog T_CUSTOMER_ALIPAY_ORDER_NO_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerAlipayOrderNoLog.T_CUSTOMER_ALIPAY_ORDER_NO_LOG;

    /**
     * The table <code>db_mall.t_customer_balance_date_log</code>.
     */
    public final TCustomerBalanceDateLog T_CUSTOMER_BALANCE_DATE_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerBalanceDateLog.T_CUSTOMER_BALANCE_DATE_LOG;

    /**
     * The table <code>db_mall.t_customer_bill</code>.
     */
    public final TCustomerBill T_CUSTOMER_BILL = cn.zyj.dbexporter.jooq.tables.TCustomerBill.T_CUSTOMER_BILL;

    /**
     * The table <code>db_mall.t_customer_bill_month</code>.
     */
    public final TCustomerBillMonth T_CUSTOMER_BILL_MONTH = cn.zyj.dbexporter.jooq.tables.TCustomerBillMonth.T_CUSTOMER_BILL_MONTH;

    /**
     * The table <code>db_mall.t_customer_bill_month_proof</code>.
     */
    public final TCustomerBillMonthProof T_CUSTOMER_BILL_MONTH_PROOF = cn.zyj.dbexporter.jooq.tables.TCustomerBillMonthProof.T_CUSTOMER_BILL_MONTH_PROOF;

    /**
     * The table <code>db_mall.t_customer_black</code>.
     */
    public final TCustomerBlack T_CUSTOMER_BLACK = cn.zyj.dbexporter.jooq.tables.TCustomerBlack.T_CUSTOMER_BLACK;

    /**
     * The table <code>db_mall.t_customer_coupon</code>.
     */
    public final TCustomerCoupon T_CUSTOMER_COUPON = cn.zyj.dbexporter.jooq.tables.TCustomerCoupon.T_CUSTOMER_COUPON;

    /**
     * The table <code>db_mall.t_customer_credit_balance_event</code>.
     */
    public final TCustomerCreditBalanceEvent T_CUSTOMER_CREDIT_BALANCE_EVENT = cn.zyj.dbexporter.jooq.tables.TCustomerCreditBalanceEvent.T_CUSTOMER_CREDIT_BALANCE_EVENT;

    /**
     * The table <code>db_mall.t_customer_crm_paytype_band_log</code>.
     */
    public final TCustomerCrmPaytypeBandLog T_CUSTOMER_CRM_PAYTYPE_BAND_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerCrmPaytypeBandLog.T_CUSTOMER_CRM_PAYTYPE_BAND_LOG;

    /**
     * The table <code>db_mall.t_customer_hint</code>.
     */
    public final TCustomerHint T_CUSTOMER_HINT = cn.zyj.dbexporter.jooq.tables.TCustomerHint.T_CUSTOMER_HINT;

    /**
     * The table <code>db_mall.t_customer_invoice_based_bill</code>.
     */
    public final TCustomerInvoiceBasedBill T_CUSTOMER_INVOICE_BASED_BILL = cn.zyj.dbexporter.jooq.tables.TCustomerInvoiceBasedBill.T_CUSTOMER_INVOICE_BASED_BILL;

    /**
     * The table <code>db_mall.t_customer_login_log</code>.
     */
    public final TCustomerLoginLog T_CUSTOMER_LOGIN_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerLoginLog.T_CUSTOMER_LOGIN_LOG;

    /**
     * The table <code>db_mall.t_customer_member_invite</code>.
     */
    public final TCustomerMemberInvite T_CUSTOMER_MEMBER_INVITE = cn.zyj.dbexporter.jooq.tables.TCustomerMemberInvite.T_CUSTOMER_MEMBER_INVITE;

    /**
     * The table <code>db_mall.t_customer_notice</code>.
     */
    public final TCustomerNotice T_CUSTOMER_NOTICE = cn.zyj.dbexporter.jooq.tables.TCustomerNotice.T_CUSTOMER_NOTICE;

    /**
     * The table <code>db_mall.t_customer_passwd_change_log</code>.
     */
    public final TCustomerPasswdChangeLog T_CUSTOMER_PASSWD_CHANGE_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerPasswdChangeLog.T_CUSTOMER_PASSWD_CHANGE_LOG;

    /**
     * The table <code>db_mall.t_customer_phone_change_log</code>.
     */
    public final TCustomerPhoneChangeLog T_CUSTOMER_PHONE_CHANGE_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerPhoneChangeLog.T_CUSTOMER_PHONE_CHANGE_LOG;

    /**
     * The table <code>db_mall.t_customer_product_limit</code>.
     */
    public final TCustomerProductLimit T_CUSTOMER_PRODUCT_LIMIT = cn.zyj.dbexporter.jooq.tables.TCustomerProductLimit.T_CUSTOMER_PRODUCT_LIMIT;

    /**
     * The table <code>db_mall.t_customer_remark_log</code>.
     */
    public final TCustomerRemarkLog T_CUSTOMER_REMARK_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerRemarkLog.T_CUSTOMER_REMARK_LOG;

    /**
     * The table <code>db_mall.t_customer_say</code>.
     */
    public final TCustomerSay T_CUSTOMER_SAY = cn.zyj.dbexporter.jooq.tables.TCustomerSay.T_CUSTOMER_SAY;

    /**
     * The table <code>db_mall.t_customer_sms_code</code>.
     */
    public final TCustomerSmsCode T_CUSTOMER_SMS_CODE = cn.zyj.dbexporter.jooq.tables.TCustomerSmsCode.T_CUSTOMER_SMS_CODE;

    /**
     * The table <code>db_mall.t_customer_sms_code_copy</code>.
     */
    public final TCustomerSmsCodeCopy T_CUSTOMER_SMS_CODE_COPY = cn.zyj.dbexporter.jooq.tables.TCustomerSmsCodeCopy.T_CUSTOMER_SMS_CODE_COPY;

    /**
     * The table <code>db_mall.t_customer_status_log</code>.
     */
    public final TCustomerStatusLog T_CUSTOMER_STATUS_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerStatusLog.T_CUSTOMER_STATUS_LOG;

    /**
     * 易点租2017行业峰会 人员记录表
     */
    public final TCustomerSummitInfo T_CUSTOMER_SUMMIT_INFO = cn.zyj.dbexporter.jooq.tables.TCustomerSummitInfo.T_CUSTOMER_SUMMIT_INFO;

    /**
     * 客户跳转至saas日志记录表
     */
    public final TCustomerToSaasLog T_CUSTOMER_TO_SAAS_LOG = cn.zyj.dbexporter.jooq.tables.TCustomerToSaasLog.T_CUSTOMER_TO_SAAS_LOG;

    /**
     * The table <code>db_mall.t_customer_wechat</code>.
     */
    public final TCustomerWechat T_CUSTOMER_WECHAT = cn.zyj.dbexporter.jooq.tables.TCustomerWechat.T_CUSTOMER_WECHAT;

    /**
     * The table <code>db_mall.t_customer_withdraw</code>.
     */
    public final TCustomerWithdraw T_CUSTOMER_WITHDRAW = cn.zyj.dbexporter.jooq.tables.TCustomerWithdraw.T_CUSTOMER_WITHDRAW;

    /**
     * 押金全付+用押金抵扣租金的方式的订单表
     */
    public final TCutbillDepositOrder T_CUTBILL_DEPOSIT_ORDER = cn.zyj.dbexporter.jooq.tables.TCutbillDepositOrder.T_CUTBILL_DEPOSIT_ORDER;

    /**
     * The table <code>db_mall.t_cut_money_day</code>.
     */
    public final TCutMoneyDay T_CUT_MONEY_DAY = cn.zyj.dbexporter.jooq.tables.TCutMoneyDay.T_CUT_MONEY_DAY;

    /**
     * The table <code>db_mall.t_device_allocate</code>.
     */
    public final TDeviceAllocate T_DEVICE_ALLOCATE = cn.zyj.dbexporter.jooq.tables.TDeviceAllocate.T_DEVICE_ALLOCATE;

    /**
     * The table <code>db_mall.t_dynamic_customer_cut_money_date_log</code>.
     */
    public final TDynamicCustomerCutMoneyDateLog T_DYNAMIC_CUSTOMER_CUT_MONEY_DATE_LOG = cn.zyj.dbexporter.jooq.tables.TDynamicCustomerCutMoneyDateLog.T_DYNAMIC_CUSTOMER_CUT_MONEY_DATE_LOG;

    /**
     * The table <code>db_mall.t_equipment_event</code>.
     */
    public final TEquipmentEvent T_EQUIPMENT_EVENT = cn.zyj.dbexporter.jooq.tables.TEquipmentEvent.T_EQUIPMENT_EVENT;

    /**
     * 设备事件变化历史记录表
     */
    public final TEquipmentTransLog T_EQUIPMENT_TRANS_LOG = cn.zyj.dbexporter.jooq.tables.TEquipmentTransLog.T_EQUIPMENT_TRANS_LOG;

    /**
     * The table <code>db_mall.t_erp_sku</code>.
     */
    public final TErpSku T_ERP_SKU = cn.zyj.dbexporter.jooq.tables.TErpSku.T_ERP_SKU;

    /**
     * The table <code>db_mall.t_erp_spu</code>.
     */
    public final TErpSpu T_ERP_SPU = cn.zyj.dbexporter.jooq.tables.TErpSpu.T_ERP_SPU;

    /**
     * The table <code>db_mall.t_every_day</code>.
     */
    public final TEveryDay T_EVERY_DAY = cn.zyj.dbexporter.jooq.tables.TEveryDay.T_EVERY_DAY;

    /**
     * The table <code>db_mall.t_fix_paydate_log</code>.
     */
    public final TFixPaydateLog T_FIX_PAYDATE_LOG = cn.zyj.dbexporter.jooq.tables.TFixPaydateLog.T_FIX_PAYDATE_LOG;

    /**
     * The table <code>db_mall.t_frozen_money_deposit</code>.
     */
    public final TFrozenMoneyDeposit T_FROZEN_MONEY_DEPOSIT = cn.zyj.dbexporter.jooq.tables.TFrozenMoneyDeposit.T_FROZEN_MONEY_DEPOSIT;

    /**
     * The table <code>db_mall.t_groups</code>.
     */
    public final TGroups T_GROUPS = cn.zyj.dbexporter.jooq.tables.TGroups.T_GROUPS;

    /**
     * The table <code>db_mall.t_group_account</code>.
     */
    public final TGroupAccount T_GROUP_ACCOUNT = cn.zyj.dbexporter.jooq.tables.TGroupAccount.T_GROUP_ACCOUNT;

    /**
     * The table <code>db_mall.t_group_accounts</code>.
     */
    public final TGroupAccounts T_GROUP_ACCOUNTS = cn.zyj.dbexporter.jooq.tables.TGroupAccounts.T_GROUP_ACCOUNTS;

    /**
     * The table <code>db_mall.t_group_account_rela</code>.
     */
    public final TGroupAccountRela T_GROUP_ACCOUNT_RELA = cn.zyj.dbexporter.jooq.tables.TGroupAccountRela.T_GROUP_ACCOUNT_RELA;

    /**
     * The table <code>db_mall.t_group_apply</code>.
     */
    public final TGroupApply T_GROUP_APPLY = cn.zyj.dbexporter.jooq.tables.TGroupApply.T_GROUP_APPLY;

    /**
     * The table <code>db_mall.t_group_child_function_status</code>.
     */
    public final TGroupChildFunctionStatus T_GROUP_CHILD_FUNCTION_STATUS = cn.zyj.dbexporter.jooq.tables.TGroupChildFunctionStatus.T_GROUP_CHILD_FUNCTION_STATUS;

    /**
     * The table <code>db_mall.t_group_child_order_verify</code>.
     */
    public final TGroupChildOrderVerify T_GROUP_CHILD_ORDER_VERIFY = cn.zyj.dbexporter.jooq.tables.TGroupChildOrderVerify.T_GROUP_CHILD_ORDER_VERIFY;

    /**
     * The table <code>db_mall.t_group_customer_oper_log</code>.
     */
    public final TGroupCustomerOperLog T_GROUP_CUSTOMER_OPER_LOG = cn.zyj.dbexporter.jooq.tables.TGroupCustomerOperLog.T_GROUP_CUSTOMER_OPER_LOG;

    /**
     * The table <code>db_mall.t_group_permission</code>.
     */
    public final TGroupPermission T_GROUP_PERMISSION = cn.zyj.dbexporter.jooq.tables.TGroupPermission.T_GROUP_PERMISSION;

    /**
     * The table <code>db_mall.t_group_permission_rela</code>.
     */
    public final TGroupPermissionRela T_GROUP_PERMISSION_RELA = cn.zyj.dbexporter.jooq.tables.TGroupPermissionRela.T_GROUP_PERMISSION_RELA;

    /**
     * 代客下单日志记录
     */
    public final THelpCustomerOrderLog T_HELP_CUSTOMER_ORDER_LOG = cn.zyj.dbexporter.jooq.tables.THelpCustomerOrderLog.T_HELP_CUSTOMER_ORDER_LOG;

    /**
     * 代客下单日志记录明细
     */
    public final THelpCustomerOrderLogDetail T_HELP_CUSTOMER_ORDER_LOG_DETAIL = cn.zyj.dbexporter.jooq.tables.THelpCustomerOrderLogDetail.T_HELP_CUSTOMER_ORDER_LOG_DETAIL;

    /**
     * The table <code>db_mall.t_home_floor</code>.
     */
    public final THomeFloor T_HOME_FLOOR = cn.zyj.dbexporter.jooq.tables.THomeFloor.T_HOME_FLOOR;

    /**
     * The table <code>db_mall.t_home_product</code>.
     */
    public final THomeProduct T_HOME_PRODUCT = cn.zyj.dbexporter.jooq.tables.THomeProduct.T_HOME_PRODUCT;

    /**
     * The table <code>db_mall.t_index_floor</code>.
     */
    public final TIndexFloor T_INDEX_FLOOR = cn.zyj.dbexporter.jooq.tables.TIndexFloor.T_INDEX_FLOOR;

    /**
     * The table <code>db_mall.t_index_floor_copy</code>.
     */
    public final TIndexFloorCopy T_INDEX_FLOOR_COPY = cn.zyj.dbexporter.jooq.tables.TIndexFloorCopy.T_INDEX_FLOOR_COPY;

    /**
     * The table <code>db_mall.t_index_product</code>.
     */
    public final TIndexProduct T_INDEX_PRODUCT = cn.zyj.dbexporter.jooq.tables.TIndexProduct.T_INDEX_PRODUCT;

    /**
     * The table <code>db_mall.t_index_product_copy</code>.
     */
    public final TIndexProductCopy T_INDEX_PRODUCT_COPY = cn.zyj.dbexporter.jooq.tables.TIndexProductCopy.T_INDEX_PRODUCT_COPY;

    /**
     * The table <code>db_mall.t_invoice_detail</code>.
     */
    public final TInvoiceDetail T_INVOICE_DETAIL = cn.zyj.dbexporter.jooq.tables.TInvoiceDetail.T_INVOICE_DETAIL;

    /**
     * 发票提醒文案
     */
    public final TInvoiceNotice T_INVOICE_NOTICE = cn.zyj.dbexporter.jooq.tables.TInvoiceNotice.T_INVOICE_NOTICE;

    /**
     * The table <code>db_mall.t_invoice_request</code>.
     */
    public final TInvoiceRequest T_INVOICE_REQUEST = cn.zyj.dbexporter.jooq.tables.TInvoiceRequest.T_INVOICE_REQUEST;

    /**
     * The table <code>db_mall.t_invoice_request_event</code>.
     */
    public final TInvoiceRequestEvent T_INVOICE_REQUEST_EVENT = cn.zyj.dbexporter.jooq.tables.TInvoiceRequestEvent.T_INVOICE_REQUEST_EVENT;

    /**
     * The table <code>db_mall.t_invoice_request_over_log</code>.
     */
    public final TInvoiceRequestOverLog T_INVOICE_REQUEST_OVER_LOG = cn.zyj.dbexporter.jooq.tables.TInvoiceRequestOverLog.T_INVOICE_REQUEST_OVER_LOG;

    /**
     * The table <code>db_mall.t_loop_logo</code>.
     */
    public final TLoopLogo T_LOOP_LOGO = cn.zyj.dbexporter.jooq.tables.TLoopLogo.T_LOOP_LOGO;

    /**
     * The table <code>db_mall.t_mac_bind_log</code>.
     */
    public final TMacBindLog T_MAC_BIND_LOG = cn.zyj.dbexporter.jooq.tables.TMacBindLog.T_MAC_BIND_LOG;

    /**
     * The table <code>db_mall.t_mac_device</code>.
     */
    public final TMacDevice T_MAC_DEVICE = cn.zyj.dbexporter.jooq.tables.TMacDevice.T_MAC_DEVICE;

    /**
     * The table <code>db_mall.t_mac_log</code>.
     */
    public final TMacLog T_MAC_LOG = cn.zyj.dbexporter.jooq.tables.TMacLog.T_MAC_LOG;

    /**
     * 管理员表
     */
    public final TManager T_MANAGER = cn.zyj.dbexporter.jooq.tables.TManager.T_MANAGER;

    /**
     * 管理员文件表
     */
    public final TManagerFile T_MANAGER_FILE = cn.zyj.dbexporter.jooq.tables.TManagerFile.T_MANAGER_FILE;

    /**
     * 管理员日志表
     */
    public final TManagerLog T_MANAGER_LOG = cn.zyj.dbexporter.jooq.tables.TManagerLog.T_MANAGER_LOG;

    /**
     * 菜单表
     */
    public final TMenu T_MENU = cn.zyj.dbexporter.jooq.tables.TMenu.T_MENU;

    /**
     * The table <code>db_mall.t_message_notice</code>.
     */
    public final TMessageNotice T_MESSAGE_NOTICE = cn.zyj.dbexporter.jooq.tables.TMessageNotice.T_MESSAGE_NOTICE;

    /**
     * The table <code>db_mall.t_net_recharge_list</code>.
     */
    public final TNetRechargeList T_NET_RECHARGE_LIST = cn.zyj.dbexporter.jooq.tables.TNetRechargeList.T_NET_RECHARGE_LIST;

    /**
     * The table <code>db_mall.t_net_recharge_request</code>.
     */
    public final TNetRechargeRequest T_NET_RECHARGE_REQUEST = cn.zyj.dbexporter.jooq.tables.TNetRechargeRequest.T_NET_RECHARGE_REQUEST;

    /**
     * The table <code>db_mall.t_news_category</code>.
     */
    public final TNewsCategory T_NEWS_CATEGORY = cn.zyj.dbexporter.jooq.tables.TNewsCategory.T_NEWS_CATEGORY;

    /**
     * The table <code>db_mall.t_news_content</code>.
     */
    public final TNewsContent T_NEWS_CONTENT = cn.zyj.dbexporter.jooq.tables.TNewsContent.T_NEWS_CONTENT;

    /**
     * The table <code>db_mall.t_offer_goods</code>.
     */
    public final TOfferGoods T_OFFER_GOODS = cn.zyj.dbexporter.jooq.tables.TOfferGoods.T_OFFER_GOODS;

    /**
     * The table <code>db_mall.t_op_logs</code>.
     */
    public final TOpLogs T_OP_LOGS = cn.zyj.dbexporter.jooq.tables.TOpLogs.T_OP_LOGS;

    /**
     * The table <code>db_mall.t_orders</code>.
     */
    public final TOrders T_ORDERS = cn.zyj.dbexporter.jooq.tables.TOrders.T_ORDERS;

    /**
     * The table <code>db_mall.t_order_balance</code>.
     */
    public final TOrderBalance T_ORDER_BALANCE = cn.zyj.dbexporter.jooq.tables.TOrderBalance.T_ORDER_BALANCE;

    /**
     * The table <code>db_mall.t_order_bill</code>.
     */
    public final TOrderBill T_ORDER_BILL = cn.zyj.dbexporter.jooq.tables.TOrderBill.T_ORDER_BILL;

    /**
     * The table <code>db_mall.t_order_bill_change_log</code>.
     */
    public final TOrderBillChangeLog T_ORDER_BILL_CHANGE_LOG = cn.zyj.dbexporter.jooq.tables.TOrderBillChangeLog.T_ORDER_BILL_CHANGE_LOG;

    /**
     * The table <code>db_mall.t_order_bill_confirm</code>.
     */
    public final TOrderBillConfirm T_ORDER_BILL_CONFIRM = cn.zyj.dbexporter.jooq.tables.TOrderBillConfirm.T_ORDER_BILL_CONFIRM;

    /**
     * The table <code>db_mall.t_order_bill_cut_money_date_log</code>.
     */
    public final TOrderBillCutMoneyDateLog T_ORDER_BILL_CUT_MONEY_DATE_LOG = cn.zyj.dbexporter.jooq.tables.TOrderBillCutMoneyDateLog.T_ORDER_BILL_CUT_MONEY_DATE_LOG;

    /**
     * The table <code>db_mall.t_order_bill_detail</code>.
     */
    public final TOrderBillDetail T_ORDER_BILL_DETAIL = cn.zyj.dbexporter.jooq.tables.TOrderBillDetail.T_ORDER_BILL_DETAIL;

    /**
     * The table <code>db_mall.t_order_change_rent</code>.
     */
    public final TOrderChangeRent T_ORDER_CHANGE_RENT = cn.zyj.dbexporter.jooq.tables.TOrderChangeRent.T_ORDER_CHANGE_RENT;

    /**
     * The table <code>db_mall.t_order_change_start_rent_log</code>.
     */
    public final TOrderChangeStartRentLog T_ORDER_CHANGE_START_RENT_LOG = cn.zyj.dbexporter.jooq.tables.TOrderChangeStartRentLog.T_ORDER_CHANGE_START_RENT_LOG;

    /**
     * The table <code>db_mall.t_order_count</code>.
     */
    public final TOrderCount T_ORDER_COUNT = cn.zyj.dbexporter.jooq.tables.TOrderCount.T_ORDER_COUNT;

    /**
     * The table <code>db_mall.t_order_coupon</code>.
     */
    public final TOrderCoupon T_ORDER_COUPON = cn.zyj.dbexporter.jooq.tables.TOrderCoupon.T_ORDER_COUPON;

    /**
     * The table <code>db_mall.t_order_create_fail</code>.
     */
    public final TOrderCreateFail T_ORDER_CREATE_FAIL = cn.zyj.dbexporter.jooq.tables.TOrderCreateFail.T_ORDER_CREATE_FAIL;

    /**
     * 订单事件记录表
     */
    public final TOrderEvent T_ORDER_EVENT = cn.zyj.dbexporter.jooq.tables.TOrderEvent.T_ORDER_EVENT;

    /**
     * The table <code>db_mall.t_order_exchange</code>.
     */
    public final TOrderExchange T_ORDER_EXCHANGE = cn.zyj.dbexporter.jooq.tables.TOrderExchange.T_ORDER_EXCHANGE;

    /**
     * The table <code>db_mall.t_order_express</code>.
     */
    public final TOrderExpress T_ORDER_EXPRESS = cn.zyj.dbexporter.jooq.tables.TOrderExpress.T_ORDER_EXPRESS;

    /**
     * The table <code>db_mall.t_order_items</code>.
     */
    public final TOrderItems T_ORDER_ITEMS = cn.zyj.dbexporter.jooq.tables.TOrderItems.T_ORDER_ITEMS;

    /**
     * The table <code>db_mall.t_order_items_detail</code>.
     */
    public final TOrderItemsDetail T_ORDER_ITEMS_DETAIL = cn.zyj.dbexporter.jooq.tables.TOrderItemsDetail.T_ORDER_ITEMS_DETAIL;

    /**
     * The table <code>db_mall.t_order_items_detail_log</code>.
     */
    public final TOrderItemsDetailLog T_ORDER_ITEMS_DETAIL_LOG = cn.zyj.dbexporter.jooq.tables.TOrderItemsDetailLog.T_ORDER_ITEMS_DETAIL_LOG;

    /**
     * The table <code>db_mall.t_order_items_detail_return_log</code>.
     */
    public final TOrderItemsDetailReturnLog T_ORDER_ITEMS_DETAIL_RETURN_LOG = cn.zyj.dbexporter.jooq.tables.TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG;

    /**
     * The table <code>db_mall.t_order_news</code>.
     */
    public final TOrderNews T_ORDER_NEWS = cn.zyj.dbexporter.jooq.tables.TOrderNews.T_ORDER_NEWS;

    /**
     * The table <code>db_mall.t_order_payable_bill</code>.
     */
    public final TOrderPayableBill T_ORDER_PAYABLE_BILL = cn.zyj.dbexporter.jooq.tables.TOrderPayableBill.T_ORDER_PAYABLE_BILL;

    /**
     * The table <code>db_mall.t_order_pay_event</code>.
     */
    public final TOrderPayEvent T_ORDER_PAY_EVENT = cn.zyj.dbexporter.jooq.tables.TOrderPayEvent.T_ORDER_PAY_EVENT;

    /**
     * The table <code>db_mall.t_order_product_sku</code>.
     */
    public final TOrderProductSku T_ORDER_PRODUCT_SKU = cn.zyj.dbexporter.jooq.tables.TOrderProductSku.T_ORDER_PRODUCT_SKU;

    /**
     * The table <code>db_mall.t_order_queue</code>.
     */
    public final TOrderQueue T_ORDER_QUEUE = cn.zyj.dbexporter.jooq.tables.TOrderQueue.T_ORDER_QUEUE;

    /**
     * The table <code>db_mall.t_order_refund</code>.
     */
    public final TOrderRefund T_ORDER_REFUND = cn.zyj.dbexporter.jooq.tables.TOrderRefund.T_ORDER_REFUND;

    /**
     * The table <code>db_mall.t_order_renew_log</code>.
     */
    public final TOrderRenewLog T_ORDER_RENEW_LOG = cn.zyj.dbexporter.jooq.tables.TOrderRenewLog.T_ORDER_RENEW_LOG;

    /**
     * The table <code>db_mall.t_order_rent_type_change_log</code>.
     */
    public final TOrderRentTypeChangeLog T_ORDER_RENT_TYPE_CHANGE_LOG = cn.zyj.dbexporter.jooq.tables.TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG;

    /**
     * The table <code>db_mall.t_order_repay</code>.
     */
    public final TOrderRepay T_ORDER_REPAY = cn.zyj.dbexporter.jooq.tables.TOrderRepay.T_ORDER_REPAY;

    /**
     * The table <code>db_mall.t_order_search</code>.
     */
    public final TOrderSearch T_ORDER_SEARCH = cn.zyj.dbexporter.jooq.tables.TOrderSearch.T_ORDER_SEARCH;

    /**
     * The table <code>db_mall.t_order_share</code>.
     */
    public final TOrderShare T_ORDER_SHARE = cn.zyj.dbexporter.jooq.tables.TOrderShare.T_ORDER_SHARE;

    /**
     * The table <code>db_mall.t_order_trans_log</code>.
     */
    public final TOrderTransLog T_ORDER_TRANS_LOG = cn.zyj.dbexporter.jooq.tables.TOrderTransLog.T_ORDER_TRANS_LOG;

    /**
     * The table <code>db_mall.t_overdue_customer</code>.
     */
    public final TOverdueCustomer T_OVERDUE_CUSTOMER = cn.zyj.dbexporter.jooq.tables.TOverdueCustomer.T_OVERDUE_CUSTOMER;

    /**
     * The table <code>db_mall.t_phone_temp</code>.
     */
    public final TPhoneTemp T_PHONE_TEMP = cn.zyj.dbexporter.jooq.tables.TPhoneTemp.T_PHONE_TEMP;

    /**
     * The table <code>db_mall.t_pic_patch_list</code>.
     */
    public final TPicPatchList T_PIC_PATCH_LIST = cn.zyj.dbexporter.jooq.tables.TPicPatchList.T_PIC_PATCH_LIST;

    /**
     * The table <code>db_mall.t_price_calc</code>.
     */
    public final TPriceCalc T_PRICE_CALC = cn.zyj.dbexporter.jooq.tables.TPriceCalc.T_PRICE_CALC;

    /**
     * The table <code>db_mall.t_product_assemble</code>.
     */
    public final TProductAssemble T_PRODUCT_ASSEMBLE = cn.zyj.dbexporter.jooq.tables.TProductAssemble.T_PRODUCT_ASSEMBLE;

    /**
     * The table <code>db_mall.t_product_assemble_copy</code>.
     */
    public final TProductAssembleCopy T_PRODUCT_ASSEMBLE_COPY = cn.zyj.dbexporter.jooq.tables.TProductAssembleCopy.T_PRODUCT_ASSEMBLE_COPY;

    /**
     * 商品品牌表
     */
    public final TProductBrand T_PRODUCT_BRAND = cn.zyj.dbexporter.jooq.tables.TProductBrand.T_PRODUCT_BRAND;

    /**
     * 商品分类表
     */
    public final TProductCategory T_PRODUCT_CATEGORY = cn.zyj.dbexporter.jooq.tables.TProductCategory.T_PRODUCT_CATEGORY;

    /**
     * The table <code>db_mall.t_product_category_classification_attr</code>.
     */
    public final TProductCategoryClassificationAttr T_PRODUCT_CATEGORY_CLASSIFICATION_ATTR = cn.zyj.dbexporter.jooq.tables.TProductCategoryClassificationAttr.T_PRODUCT_CATEGORY_CLASSIFICATION_ATTR;

    /**
     * The table <code>db_mall.t_product_change</code>.
     */
    public final TProductChange T_PRODUCT_CHANGE = cn.zyj.dbexporter.jooq.tables.TProductChange.T_PRODUCT_CHANGE;

    /**
     * The table <code>db_mall.t_product_check</code>.
     */
    public final TProductCheck T_PRODUCT_CHECK = cn.zyj.dbexporter.jooq.tables.TProductCheck.T_PRODUCT_CHECK;

    /**
     * The table <code>db_mall.t_product_describe_list</code>.
     */
    public final TProductDescribeList T_PRODUCT_DESCRIBE_LIST = cn.zyj.dbexporter.jooq.tables.TProductDescribeList.T_PRODUCT_DESCRIBE_LIST;

    /**
     * The table <code>db_mall.t_product_ghost</code>.
     */
    public final TProductGhost T_PRODUCT_GHOST = cn.zyj.dbexporter.jooq.tables.TProductGhost.T_PRODUCT_GHOST;

    /**
     * The table <code>db_mall.t_product_image</code>.
     */
    public final TProductImage T_PRODUCT_IMAGE = cn.zyj.dbexporter.jooq.tables.TProductImage.T_PRODUCT_IMAGE;

    /**
     * The table <code>db_mall.t_product_key</code>.
     */
    public final TProductKey T_PRODUCT_KEY = cn.zyj.dbexporter.jooq.tables.TProductKey.T_PRODUCT_KEY;

    /**
     * The table <code>db_mall.t_product_list</code>.
     */
    public final TProductList T_PRODUCT_LIST = cn.zyj.dbexporter.jooq.tables.TProductList.T_PRODUCT_LIST;

    /**
     * The table <code>db_mall.t_product_lis_01</code>.
     */
    public final TProductLis_01 T_PRODUCT_LIS_01 = cn.zyj.dbexporter.jooq.tables.TProductLis_01.T_PRODUCT_LIS_01;

    /**
     * The table <code>db_mall.t_product_lis_copy</code>.
     */
    public final TProductLisCopy T_PRODUCT_LIS_COPY = cn.zyj.dbexporter.jooq.tables.TProductLisCopy.T_PRODUCT_LIS_COPY;

    /**
     * The table <code>db_mall.t_product_major_other_param</code>.
     */
    public final TProductMajorOtherParam T_PRODUCT_MAJOR_OTHER_PARAM = cn.zyj.dbexporter.jooq.tables.TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM;

    /**
     * The table <code>db_mall.t_product_major_param</code>.
     */
    public final TProductMajorParam T_PRODUCT_MAJOR_PARAM = cn.zyj.dbexporter.jooq.tables.TProductMajorParam.T_PRODUCT_MAJOR_PARAM;

    /**
     * The table <code>db_mall.t_product_qa</code>.
     */
    public final TProductQa T_PRODUCT_QA = cn.zyj.dbexporter.jooq.tables.TProductQa.T_PRODUCT_QA;

    /**
     * The table <code>db_mall.t_product_relet</code>.
     */
    public final TProductRelet T_PRODUCT_RELET = cn.zyj.dbexporter.jooq.tables.TProductRelet.T_PRODUCT_RELET;

    /**
     * The table <code>db_mall.t_product_rent_type</code>.
     */
    public final TProductRentType T_PRODUCT_RENT_TYPE = cn.zyj.dbexporter.jooq.tables.TProductRentType.T_PRODUCT_RENT_TYPE;

    /**
     * The table <code>db_mall.t_product_rent_type_detail</code>.
     */
    public final TProductRentTypeDetail T_PRODUCT_RENT_TYPE_DETAIL = cn.zyj.dbexporter.jooq.tables.TProductRentTypeDetail.T_PRODUCT_RENT_TYPE_DETAIL;

    /**
     * The table <code>db_mall.t_product_skuid_info</code>.
     */
    public final TProductSkuidInfo T_PRODUCT_SKUID_INFO = cn.zyj.dbexporter.jooq.tables.TProductSkuidInfo.T_PRODUCT_SKUID_INFO;

    /**
     * The table <code>db_mall.t_product_status</code>.
     */
    public final TProductStatus T_PRODUCT_STATUS = cn.zyj.dbexporter.jooq.tables.TProductStatus.T_PRODUCT_STATUS;

    /**
     * 商品库存提醒队列
     */
    public final TProductStockNoticeQueue T_PRODUCT_STOCK_NOTICE_QUEUE = cn.zyj.dbexporter.jooq.tables.TProductStockNoticeQueue.T_PRODUCT_STOCK_NOTICE_QUEUE;

    /**
     * The table <code>db_mall.t_product_stock_queue</code>.
     */
    public final TProductStockQueue T_PRODUCT_STOCK_QUEUE = cn.zyj.dbexporter.jooq.tables.TProductStockQueue.T_PRODUCT_STOCK_QUEUE;

    /**
     * The table <code>db_mall.t_province</code>.
     */
    public final TProvince T_PROVINCE = cn.zyj.dbexporter.jooq.tables.TProvince.T_PROVINCE;

    /**
     * The table <code>db_mall.t_quartz_monitor</code>.
     */
    public final TQuartzMonitor T_QUARTZ_MONITOR = cn.zyj.dbexporter.jooq.tables.TQuartzMonitor.T_QUARTZ_MONITOR;

    /**
     * The table <code>db_mall.t_query</code>.
     */
    public final TQuery T_QUERY = cn.zyj.dbexporter.jooq.tables.TQuery.T_QUERY;

    /**
     * The table <code>db_mall.t_recycle_apply</code>.
     */
    public final TRecycleApply T_RECYCLE_APPLY = cn.zyj.dbexporter.jooq.tables.TRecycleApply.T_RECYCLE_APPLY;

    /**
     * The table <code>db_mall.t_recycle_options</code>.
     */
    public final TRecycleOptions T_RECYCLE_OPTIONS = cn.zyj.dbexporter.jooq.tables.TRecycleOptions.T_RECYCLE_OPTIONS;

    /**
     * The table <code>db_mall.t_release_frozen_balance</code>.
     */
    public final TReleaseFrozenBalance T_RELEASE_FROZEN_BALANCE = cn.zyj.dbexporter.jooq.tables.TReleaseFrozenBalance.T_RELEASE_FROZEN_BALANCE;

    /**
     * 权限表
     */
    public final TRight T_RIGHT = cn.zyj.dbexporter.jooq.tables.TRight.T_RIGHT;

    /**
     * The table <code>db_mall.t_risk_customer_info</code>.
     */
    public final TRiskCustomerInfo T_RISK_CUSTOMER_INFO = cn.zyj.dbexporter.jooq.tables.TRiskCustomerInfo.T_RISK_CUSTOMER_INFO;

    /**
     * The table <code>db_mall.t_risk_tel_id</code>.
     */
    public final TRiskTelId T_RISK_TEL_ID = cn.zyj.dbexporter.jooq.tables.TRiskTelId.T_RISK_TEL_ID;

    /**
     * 角色表
     */
    public final TRole T_ROLE = cn.zyj.dbexporter.jooq.tables.TRole.T_ROLE;

    /**
     * 角色权限表
     */
    public final TRoleRight T_ROLE_RIGHT = cn.zyj.dbexporter.jooq.tables.TRoleRight.T_ROLE_RIGHT;

    /**
     * The table <code>db_mall.t_scity</code>.
     */
    public final TScity T_SCITY = cn.zyj.dbexporter.jooq.tables.TScity.T_SCITY;

    /**
     * The table <code>db_mall.t_shipment_notice</code>.
     */
    public final TShipmentNotice T_SHIPMENT_NOTICE = cn.zyj.dbexporter.jooq.tables.TShipmentNotice.T_SHIPMENT_NOTICE;

    /**
     * 快捷菜单表
     */
    public final TShortcutMenu T_SHORTCUT_MENU = cn.zyj.dbexporter.jooq.tables.TShortcutMenu.T_SHORTCUT_MENU;

    /**
     * The table <code>db_mall.t_sms_blacklist_log</code>.
     */
    public final TSmsBlacklistLog T_SMS_BLACKLIST_LOG = cn.zyj.dbexporter.jooq.tables.TSmsBlacklistLog.T_SMS_BLACKLIST_LOG;

    /**
     * The table <code>db_mall.t_sms_filter</code>.
     */
    public final TSmsFilter T_SMS_FILTER = cn.zyj.dbexporter.jooq.tables.TSmsFilter.T_SMS_FILTER;

    /**
     * The table <code>db_mall.t_sms_log</code>.
     */
    public final TSmsLog T_SMS_LOG = cn.zyj.dbexporter.jooq.tables.TSmsLog.T_SMS_LOG;

    /**
     * The table <code>db_mall.t_sms_template</code>.
     */
    public final TSmsTemplate T_SMS_TEMPLATE = cn.zyj.dbexporter.jooq.tables.TSmsTemplate.T_SMS_TEMPLATE;

    /**
     * The table <code>db_mall.t_sms_template_bak</code>.
     */
    public final TSmsTemplateBak T_SMS_TEMPLATE_BAK = cn.zyj.dbexporter.jooq.tables.TSmsTemplateBak.T_SMS_TEMPLATE_BAK;

    /**
     * 畅卓上行短信
     */
    public final TSmsUploadLog T_SMS_UPLOAD_LOG = cn.zyj.dbexporter.jooq.tables.TSmsUploadLog.T_SMS_UPLOAD_LOG;

    /**
     * The table <code>db_mall.t_stat_daily_devices</code>.
     */
    public final TStatDailyDevices T_STAT_DAILY_DEVICES = cn.zyj.dbexporter.jooq.tables.TStatDailyDevices.T_STAT_DAILY_DEVICES;

    /**
     * The table <code>db_mall.t_stat_daily_equipment</code>.
     */
    public final TStatDailyEquipment T_STAT_DAILY_EQUIPMENT = cn.zyj.dbexporter.jooq.tables.TStatDailyEquipment.T_STAT_DAILY_EQUIPMENT;

    /**
     * The table <code>db_mall.t_stat_daily_orders</code>.
     */
    public final TStatDailyOrders T_STAT_DAILY_ORDERS = cn.zyj.dbexporter.jooq.tables.TStatDailyOrders.T_STAT_DAILY_ORDERS;

    /**
     * The table <code>db_mall.t_stat_daily_users</code>.
     */
    public final TStatDailyUsers T_STAT_DAILY_USERS = cn.zyj.dbexporter.jooq.tables.TStatDailyUsers.T_STAT_DAILY_USERS;

    /**
     * The table <code>db_mall.t_test_user</code>.
     */
    public final TTestUser T_TEST_USER = cn.zyj.dbexporter.jooq.tables.TTestUser.T_TEST_USER;

    /**
     * The table <code>db_mall.t_vat_profile</code>.
     */
    public final TVatProfile T_VAT_PROFILE = cn.zyj.dbexporter.jooq.tables.TVatProfile.T_VAT_PROFILE;

    /**
     * The table <code>db_mall.t_waste_request</code>.
     */
    public final TWasteRequest T_WASTE_REQUEST = cn.zyj.dbexporter.jooq.tables.TWasteRequest.T_WASTE_REQUEST;

    /**
     * The table <code>db_mall.t_withdraw_request_event</code>.
     */
    public final TWithdrawRequestEvent T_WITHDRAW_REQUEST_EVENT = cn.zyj.dbexporter.jooq.tables.TWithdrawRequestEvent.T_WITHDRAW_REQUEST_EVENT;

    /**
     * The table <code>db_mall.t_wx_customer</code>.
     */
    public final TWxCustomer T_WX_CUSTOMER = cn.zyj.dbexporter.jooq.tables.TWxCustomer.T_WX_CUSTOMER;

    /**
     * No further instances allowed
     */
    private DbMall() {
        super("db_mall", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AssetsDevice.ASSETS_DEVICE,
            AssetsOperate.ASSETS_OPERATE,
            AssetsReceiver.ASSETS_RECEIVER,
            DjangoMigrations.DJANGO_MIGRATIONS,
            SmsBlacklist.SMS_BLACKLIST,
            SmsWhitelist.SMS_WHITELIST,
            Tickets.TICKETS,
            TAccessControlLog.T_ACCESS_CONTROL_LOG,
            TAlipayDataUploadlog.T_ALIPAY_DATA_UPLOADLOG,
            TAnnualReview.T_ANNUAL_REVIEW,
            TAssetsDevice.T_ASSETS_DEVICE,
            TAssetsDeviceBelong.T_ASSETS_DEVICE_BELONG,
            TAssetsDeviceBelongCopy.T_ASSETS_DEVICE_BELONG_COPY,
            TAssetsDeviceHistory.T_ASSETS_DEVICE_HISTORY,
            TAssetsDevicePackage.T_ASSETS_DEVICE_PACKAGE,
            TAssetsPackages.T_ASSETS_PACKAGES,
            TAutoCutMoneyQueue.T_AUTO_CUT_MONEY_QUEUE,
            TBankRechargeList.T_BANK_RECHARGE_LIST,
            TBcity.T_BCITY,
            TBillCalculateFlag.T_BILL_CALCULATE_FLAG,
            TBillCheck.T_BILL_CHECK,
            TBillCheckStart.T_BILL_CHECK_START,
            TBillCrm.T_BILL_CRM,
            TBillOverdueSmsRecords.T_BILL_OVERDUE_SMS_RECORDS,
            TCarts.T_CARTS,
            TCartsHistory.T_CARTS_HISTORY,
            TCartsLogs.T_CARTS_LOGS,
            TCouponCustomerList.T_COUPON_CUSTOMER_LIST,
            TCouponList.T_COUPON_LIST,
            TCrmOrderErrorLog.T_CRM_ORDER_ERROR_LOG,
            TCronLog.T_CRON_LOG,
            TCustomer.T_CUSTOMER,
            TCustomerAccount.T_CUSTOMER_ACCOUNT,
            TCustomerActionLogs.T_CUSTOMER_ACTION_LOGS,
            TCustomerActionLogsBak.T_CUSTOMER_ACTION_LOGS_BAK,
            TCustomerAddress.T_CUSTOMER_ADDRESS,
            TCustomerAlipayCreditResult.T_CUSTOMER_ALIPAY_CREDIT_RESULT,
            TCustomerAlipayMall.T_CUSTOMER_ALIPAY_MALL,
            TCustomerAlipayOrderNoLog.T_CUSTOMER_ALIPAY_ORDER_NO_LOG,
            TCustomerBalanceDateLog.T_CUSTOMER_BALANCE_DATE_LOG,
            TCustomerBill.T_CUSTOMER_BILL,
            TCustomerBillMonth.T_CUSTOMER_BILL_MONTH,
            TCustomerBillMonthProof.T_CUSTOMER_BILL_MONTH_PROOF,
            TCustomerBlack.T_CUSTOMER_BLACK,
            TCustomerCoupon.T_CUSTOMER_COUPON,
            TCustomerCreditBalanceEvent.T_CUSTOMER_CREDIT_BALANCE_EVENT,
            TCustomerCrmPaytypeBandLog.T_CUSTOMER_CRM_PAYTYPE_BAND_LOG,
            TCustomerHint.T_CUSTOMER_HINT,
            TCustomerInvoiceBasedBill.T_CUSTOMER_INVOICE_BASED_BILL,
            TCustomerLoginLog.T_CUSTOMER_LOGIN_LOG,
            TCustomerMemberInvite.T_CUSTOMER_MEMBER_INVITE,
            TCustomerNotice.T_CUSTOMER_NOTICE,
            TCustomerPasswdChangeLog.T_CUSTOMER_PASSWD_CHANGE_LOG,
            TCustomerPhoneChangeLog.T_CUSTOMER_PHONE_CHANGE_LOG,
            TCustomerProductLimit.T_CUSTOMER_PRODUCT_LIMIT,
            TCustomerRemarkLog.T_CUSTOMER_REMARK_LOG,
            TCustomerSay.T_CUSTOMER_SAY,
            TCustomerSmsCode.T_CUSTOMER_SMS_CODE,
            TCustomerSmsCodeCopy.T_CUSTOMER_SMS_CODE_COPY,
            TCustomerStatusLog.T_CUSTOMER_STATUS_LOG,
            TCustomerSummitInfo.T_CUSTOMER_SUMMIT_INFO,
            TCustomerToSaasLog.T_CUSTOMER_TO_SAAS_LOG,
            TCustomerWechat.T_CUSTOMER_WECHAT,
            TCustomerWithdraw.T_CUSTOMER_WITHDRAW,
            TCutbillDepositOrder.T_CUTBILL_DEPOSIT_ORDER,
            TCutMoneyDay.T_CUT_MONEY_DAY,
            TDeviceAllocate.T_DEVICE_ALLOCATE,
            TDynamicCustomerCutMoneyDateLog.T_DYNAMIC_CUSTOMER_CUT_MONEY_DATE_LOG,
            TEquipmentEvent.T_EQUIPMENT_EVENT,
            TEquipmentTransLog.T_EQUIPMENT_TRANS_LOG,
            TErpSku.T_ERP_SKU,
            TErpSpu.T_ERP_SPU,
            TEveryDay.T_EVERY_DAY,
            TFixPaydateLog.T_FIX_PAYDATE_LOG,
            TFrozenMoneyDeposit.T_FROZEN_MONEY_DEPOSIT,
            TGroups.T_GROUPS,
            TGroupAccount.T_GROUP_ACCOUNT,
            TGroupAccounts.T_GROUP_ACCOUNTS,
            TGroupAccountRela.T_GROUP_ACCOUNT_RELA,
            TGroupApply.T_GROUP_APPLY,
            TGroupChildFunctionStatus.T_GROUP_CHILD_FUNCTION_STATUS,
            TGroupChildOrderVerify.T_GROUP_CHILD_ORDER_VERIFY,
            TGroupCustomerOperLog.T_GROUP_CUSTOMER_OPER_LOG,
            TGroupPermission.T_GROUP_PERMISSION,
            TGroupPermissionRela.T_GROUP_PERMISSION_RELA,
            THelpCustomerOrderLog.T_HELP_CUSTOMER_ORDER_LOG,
            THelpCustomerOrderLogDetail.T_HELP_CUSTOMER_ORDER_LOG_DETAIL,
            THomeFloor.T_HOME_FLOOR,
            THomeProduct.T_HOME_PRODUCT,
            TIndexFloor.T_INDEX_FLOOR,
            TIndexFloorCopy.T_INDEX_FLOOR_COPY,
            TIndexProduct.T_INDEX_PRODUCT,
            TIndexProductCopy.T_INDEX_PRODUCT_COPY,
            TInvoiceDetail.T_INVOICE_DETAIL,
            TInvoiceNotice.T_INVOICE_NOTICE,
            TInvoiceRequest.T_INVOICE_REQUEST,
            TInvoiceRequestEvent.T_INVOICE_REQUEST_EVENT,
            TInvoiceRequestOverLog.T_INVOICE_REQUEST_OVER_LOG,
            TLoopLogo.T_LOOP_LOGO,
            TMacBindLog.T_MAC_BIND_LOG,
            TMacDevice.T_MAC_DEVICE,
            TMacLog.T_MAC_LOG,
            TManager.T_MANAGER,
            TManagerFile.T_MANAGER_FILE,
            TManagerLog.T_MANAGER_LOG,
            TMenu.T_MENU,
            TMessageNotice.T_MESSAGE_NOTICE,
            TNetRechargeList.T_NET_RECHARGE_LIST,
            TNetRechargeRequest.T_NET_RECHARGE_REQUEST,
            TNewsCategory.T_NEWS_CATEGORY,
            TNewsContent.T_NEWS_CONTENT,
            TOfferGoods.T_OFFER_GOODS,
            TOpLogs.T_OP_LOGS,
            TOrders.T_ORDERS,
            TOrderBalance.T_ORDER_BALANCE,
            TOrderBill.T_ORDER_BILL,
            TOrderBillChangeLog.T_ORDER_BILL_CHANGE_LOG,
            TOrderBillConfirm.T_ORDER_BILL_CONFIRM,
            TOrderBillCutMoneyDateLog.T_ORDER_BILL_CUT_MONEY_DATE_LOG,
            TOrderBillDetail.T_ORDER_BILL_DETAIL,
            TOrderChangeRent.T_ORDER_CHANGE_RENT,
            TOrderChangeStartRentLog.T_ORDER_CHANGE_START_RENT_LOG,
            TOrderCount.T_ORDER_COUNT,
            TOrderCoupon.T_ORDER_COUPON,
            TOrderCreateFail.T_ORDER_CREATE_FAIL,
            TOrderEvent.T_ORDER_EVENT,
            TOrderExchange.T_ORDER_EXCHANGE,
            TOrderExpress.T_ORDER_EXPRESS,
            TOrderItems.T_ORDER_ITEMS,
            TOrderItemsDetail.T_ORDER_ITEMS_DETAIL,
            TOrderItemsDetailLog.T_ORDER_ITEMS_DETAIL_LOG,
            TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG,
            TOrderNews.T_ORDER_NEWS,
            TOrderPayableBill.T_ORDER_PAYABLE_BILL,
            TOrderPayEvent.T_ORDER_PAY_EVENT,
            TOrderProductSku.T_ORDER_PRODUCT_SKU,
            TOrderQueue.T_ORDER_QUEUE,
            TOrderRefund.T_ORDER_REFUND,
            TOrderRenewLog.T_ORDER_RENEW_LOG,
            TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG,
            TOrderRepay.T_ORDER_REPAY,
            TOrderSearch.T_ORDER_SEARCH,
            TOrderShare.T_ORDER_SHARE,
            TOrderTransLog.T_ORDER_TRANS_LOG,
            TOverdueCustomer.T_OVERDUE_CUSTOMER,
            TPhoneTemp.T_PHONE_TEMP,
            TPicPatchList.T_PIC_PATCH_LIST,
            TPriceCalc.T_PRICE_CALC,
            TProductAssemble.T_PRODUCT_ASSEMBLE,
            TProductAssembleCopy.T_PRODUCT_ASSEMBLE_COPY,
            TProductBrand.T_PRODUCT_BRAND,
            TProductCategory.T_PRODUCT_CATEGORY,
            TProductCategoryClassificationAttr.T_PRODUCT_CATEGORY_CLASSIFICATION_ATTR,
            TProductChange.T_PRODUCT_CHANGE,
            TProductCheck.T_PRODUCT_CHECK,
            TProductDescribeList.T_PRODUCT_DESCRIBE_LIST,
            TProductGhost.T_PRODUCT_GHOST,
            TProductImage.T_PRODUCT_IMAGE,
            TProductKey.T_PRODUCT_KEY,
            TProductList.T_PRODUCT_LIST,
            TProductLis_01.T_PRODUCT_LIS_01,
            TProductLisCopy.T_PRODUCT_LIS_COPY,
            TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM,
            TProductMajorParam.T_PRODUCT_MAJOR_PARAM,
            TProductQa.T_PRODUCT_QA,
            TProductRelet.T_PRODUCT_RELET,
            TProductRentType.T_PRODUCT_RENT_TYPE,
            TProductRentTypeDetail.T_PRODUCT_RENT_TYPE_DETAIL,
            TProductSkuidInfo.T_PRODUCT_SKUID_INFO,
            TProductStatus.T_PRODUCT_STATUS,
            TProductStockNoticeQueue.T_PRODUCT_STOCK_NOTICE_QUEUE,
            TProductStockQueue.T_PRODUCT_STOCK_QUEUE,
            TProvince.T_PROVINCE,
            TQuartzMonitor.T_QUARTZ_MONITOR,
            TQuery.T_QUERY,
            TRecycleApply.T_RECYCLE_APPLY,
            TRecycleOptions.T_RECYCLE_OPTIONS,
            TReleaseFrozenBalance.T_RELEASE_FROZEN_BALANCE,
            TRight.T_RIGHT,
            TRiskCustomerInfo.T_RISK_CUSTOMER_INFO,
            TRiskTelId.T_RISK_TEL_ID,
            TRole.T_ROLE,
            TRoleRight.T_ROLE_RIGHT,
            TScity.T_SCITY,
            TShipmentNotice.T_SHIPMENT_NOTICE,
            TShortcutMenu.T_SHORTCUT_MENU,
            TSmsBlacklistLog.T_SMS_BLACKLIST_LOG,
            TSmsFilter.T_SMS_FILTER,
            TSmsLog.T_SMS_LOG,
            TSmsTemplate.T_SMS_TEMPLATE,
            TSmsTemplateBak.T_SMS_TEMPLATE_BAK,
            TSmsUploadLog.T_SMS_UPLOAD_LOG,
            TStatDailyDevices.T_STAT_DAILY_DEVICES,
            TStatDailyEquipment.T_STAT_DAILY_EQUIPMENT,
            TStatDailyOrders.T_STAT_DAILY_ORDERS,
            TStatDailyUsers.T_STAT_DAILY_USERS,
            TTestUser.T_TEST_USER,
            TVatProfile.T_VAT_PROFILE,
            TWasteRequest.T_WASTE_REQUEST,
            TWithdrawRequestEvent.T_WITHDRAW_REQUEST_EVENT,
            TWxCustomer.T_WX_CUSTOMER);
    }
}
