/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_calculator.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * sku组合关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSkuRelation implements Serializable {

    private static final long serialVersionUID = 1220268956;

    private Integer   id;
    private Integer   groupResourceId;
    private Integer   partResourceId;
    private Integer   productType;
    private Timestamp cdate;
    private Timestamp mdate;

    public TSkuRelation() {}

    public TSkuRelation(TSkuRelation value) {
        this.id = value.id;
        this.groupResourceId = value.groupResourceId;
        this.partResourceId = value.partResourceId;
        this.productType = value.productType;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TSkuRelation(
        Integer   id,
        Integer   groupResourceId,
        Integer   partResourceId,
        Integer   productType,
        Timestamp cdate,
        Timestamp mdate
    ) {
        this.id = id;
        this.groupResourceId = groupResourceId;
        this.partResourceId = partResourceId;
        this.productType = productType;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    public Integer getId() {
        return this.id;
    }

    public TSkuRelation setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getGroupResourceId() {
        return this.groupResourceId;
    }

    public TSkuRelation setGroupResourceId(Integer groupResourceId) {
        this.groupResourceId = groupResourceId;
        return this;
    }

    public Integer getPartResourceId() {
        return this.partResourceId;
    }

    public TSkuRelation setPartResourceId(Integer partResourceId) {
        this.partResourceId = partResourceId;
        return this;
    }

    public Integer getProductType() {
        return this.productType;
    }

    public TSkuRelation setProductType(Integer productType) {
        this.productType = productType;
        return this;
    }

    public Timestamp getCdate() {
        return this.cdate;
    }

    public TSkuRelation setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    public Timestamp getMdate() {
        return this.mdate;
    }

    public TSkuRelation setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSkuRelation (");

        sb.append(id);
        sb.append(", ").append(groupResourceId);
        sb.append(", ").append(partResourceId);
        sb.append(", ").append(productType);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
