/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.tables.records;


import cn.zyj.dbexporter.jooq.tables.TDeviceAllocate;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDeviceAllocateRecord extends UpdatableRecordImpl<TDeviceAllocateRecord> implements Record15<Integer, Long, Long, String, String, Long, Long, String, String, Long, String, String, BigDecimal, Timestamp, Timestamp> {

    private static final long serialVersionUID = 336998719;

    /**
     * Setter for <code>db_mall.t_device_allocate.id</code>. 自增主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.id</code>. 自增主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.main_customer_id</code>. 集团账号
     */
    public void setMainCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.main_customer_id</code>. 集团账号
     */
    public Long getMainCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.from_customer_id</code>. 调出公司id
     */
    public void setFromCustomerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.from_customer_id</code>. 调出公司id
     */
    public Long getFromCustomerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.from_company_name</code>. 调出公司名称
     */
    public void setFromCompanyName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.from_company_name</code>. 调出公司名称
     */
    public String getFromCompanyName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.from_order_id</code>. 调出公司单号
     */
    public void setFromOrderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.from_order_id</code>. 调出公司单号
     */
    public String getFromOrderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.from_item_detail_id</code>. 调出设备id
     */
    public void setFromItemDetailId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.from_item_detail_id</code>. 调出设备id
     */
    public Long getFromItemDetailId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.to_customer_id</code>. 调入公司id
     */
    public void setToCustomerId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.to_customer_id</code>. 调入公司id
     */
    public Long getToCustomerId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.to_company_name</code>. 调入公司名称
     */
    public void setToCompanyName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.to_company_name</code>. 调入公司名称
     */
    public String getToCompanyName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.to_order_id</code>. 调入公司单号
     */
    public void setToOrderId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.to_order_id</code>. 调入公司单号
     */
    public String getToOrderId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.to_item_detail_id</code>. 调入设备id
     */
    public void setToItemDetailId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.to_item_detail_id</code>. 调入设备id
     */
    public Long getToItemDetailId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.title</code>. 型号
     */
    public void setTitle(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.title</code>. 型号
     */
    public String getTitle() {
        return (String) get(10);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.sn</code>. 设备序列号
     */
    public void setSn(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.sn</code>. 设备序列号
     */
    public String getSn() {
        return (String) get(11);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.rent</code>.
     */
    public void setRent(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.rent</code>.
     */
    public BigDecimal getRent() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.cdate</code>.
     */
    public void setCdate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.cdate</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>db_mall.t_device_allocate.mdate</code>.
     */
    public void setMdate(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>db_mall.t_device_allocate.mdate</code>.
     */
    public Timestamp getMdate() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Long, Long, String, String, Long, Long, String, String, Long, String, String, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Long, Long, String, String, Long, Long, String, String, Long, String, String, BigDecimal, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.MAIN_CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.FROM_CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.FROM_COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.FROM_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.FROM_ITEM_DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.TO_CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.TO_COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.TO_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.TO_ITEM_DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.SN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.RENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.CDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return TDeviceAllocate.T_DEVICE_ALLOCATE.MDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMainCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getFromCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFromCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFromOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getFromItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getToCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getToCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getToOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getToItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getRent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMainCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getFromCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFromCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFromOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getFromItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getToCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getToCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getToOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getToItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getRent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value2(Long value) {
        setMainCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value3(Long value) {
        setFromCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value4(String value) {
        setFromCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value5(String value) {
        setFromOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value6(Long value) {
        setFromItemDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value7(Long value) {
        setToCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value8(String value) {
        setToCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value9(String value) {
        setToOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value10(Long value) {
        setToItemDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value11(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value12(String value) {
        setSn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value13(BigDecimal value) {
        setRent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value14(Timestamp value) {
        setCdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord value15(Timestamp value) {
        setMdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDeviceAllocateRecord values(Integer value1, Long value2, Long value3, String value4, String value5, Long value6, Long value7, String value8, String value9, Long value10, String value11, String value12, BigDecimal value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDeviceAllocateRecord
     */
    public TDeviceAllocateRecord() {
        super(TDeviceAllocate.T_DEVICE_ALLOCATE);
    }

    /**
     * Create a detached, initialised TDeviceAllocateRecord
     */
    public TDeviceAllocateRecord(Integer id, Long mainCustomerId, Long fromCustomerId, String fromCompanyName, String fromOrderId, Long fromItemDetailId, Long toCustomerId, String toCompanyName, String toOrderId, Long toItemDetailId, String title, String sn, BigDecimal rent, Timestamp cdate, Timestamp mdate) {
        super(TDeviceAllocate.T_DEVICE_ALLOCATE);

        set(0, id);
        set(1, mainCustomerId);
        set(2, fromCustomerId);
        set(3, fromCompanyName);
        set(4, fromOrderId);
        set(5, fromItemDetailId);
        set(6, toCustomerId);
        set(7, toCompanyName);
        set(8, toOrderId);
        set(9, toItemDetailId);
        set(10, title);
        set(11, sn);
        set(12, rent);
        set(13, cdate);
        set(14, mdate);
    }
}
