/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.tables.records;


import cn.zyj.dbexporter.jooq.tables.TEquipmentEvent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TEquipmentEventRecord extends UpdatableRecordImpl<TEquipmentEventRecord> implements Record9<String, Long, String, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 640569553;

    /**
     * Setter for <code>db_mall.t_equipment_event.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.customer</code>.
     */
    public void setCustomer(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.customer</code>.
     */
    public Long getCustomer() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.order_id</code>.
     */
    public void setOrderId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.sn</code>.
     */
    public void setSn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.sn</code>.
     */
    public String getSn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.operator</code>.
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.operator</code>.
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.event_type</code>.
     */
    public void setEventType(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.event_type</code>.
     */
    public Byte getEventType() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.operate_time</code>.
     */
    public void setOperateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.operate_time</code>.
     */
    public Timestamp getOperateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>db_mall.t_equipment_event.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_mall.t_equipment_event.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Long, String, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Long, String, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.CUSTOMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.SN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.OPERATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TEquipmentEvent.T_EQUIPMENT_EVENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getOperateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getOperateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value2(Long value) {
        setCustomer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value3(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value4(String value) {
        setSn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value6(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value7(Byte value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value8(Timestamp value) {
        setOperateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipmentEventRecord values(String value1, Long value2, String value3, String value4, String value5, String value6, Byte value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TEquipmentEventRecord
     */
    public TEquipmentEventRecord() {
        super(TEquipmentEvent.T_EQUIPMENT_EVENT);
    }

    /**
     * Create a detached, initialised TEquipmentEventRecord
     */
    public TEquipmentEventRecord(String id, Long customer, String orderId, String sn, String operator, String message, Byte eventType, Timestamp operateTime, Timestamp createTime) {
        super(TEquipmentEvent.T_EQUIPMENT_EVENT);

        set(0, id);
        set(1, customer);
        set(2, orderId);
        set(3, sn);
        set(4, operator);
        set(5, message);
        set(6, eventType);
        set(7, operateTime);
        set(8, createTime);
    }
}
