/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.tables.records;


import cn.zyj.dbexporter.jooq.tables.TOrderBillConfirm;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderBillConfirmRecord extends UpdatableRecordImpl<TOrderBillConfirmRecord> implements Record10<Long, Long, Integer, Integer, Integer, String, Short, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 703178642;

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.customer_id</code>. 用户id
     */
    public void setCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.customer_id</code>. 用户id
     */
    public Long getCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.balance_date</code>. 账单日
     */
    public void setBalanceDate(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.balance_date</code>. 账单日
     */
    public Integer getBalanceDate() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.bill_month</code>. 账单年月
     */
    public void setBillMonth(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.bill_month</code>. 账单年月
     */
    public Integer getBillMonth() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.cut_money_date</code>. 付款日
     */
    public void setCutMoneyDate(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.cut_money_date</code>. 付款日
     */
    public Integer getCutMoneyDate() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.telphone</code>. 手机号
     */
    public void setTelphone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.telphone</code>. 手机号
     */
    public String getTelphone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.bill_status</code>. 账单确认状态（0、未确认；1已确认；2有疑问）
     */
    public void setBillStatus(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.bill_status</code>. 账单确认状态（0、未确认；1已确认；2有疑问）
     */
    public Short getBillStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.cdate</code>.
     */
    public void setCdate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.cdate</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>db_mall.t_order_bill_confirm.mdate</code>.
     */
    public void setMdate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>db_mall.t_order_bill_confirm.mdate</code>.
     */
    public Timestamp getMdate() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Integer, Integer, Integer, String, Short, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Integer, Integer, Integer, String, Short, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.BALANCE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.BILL_MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.CUT_MONEY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.TELPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.BILL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.CDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TOrderBillConfirm.T_ORDER_BILL_CONFIRM.MDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getBalanceDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getBillMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCutMoneyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTelphone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getBillStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBalanceDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getBillMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCutMoneyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTelphone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getBillStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value2(Long value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value3(Integer value) {
        setBalanceDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value4(Integer value) {
        setBillMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value5(Integer value) {
        setCutMoneyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value6(String value) {
        setTelphone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value7(Short value) {
        setBillStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value9(Timestamp value) {
        setCdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord value10(Timestamp value) {
        setMdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderBillConfirmRecord values(Long value1, Long value2, Integer value3, Integer value4, Integer value5, String value6, Short value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOrderBillConfirmRecord
     */
    public TOrderBillConfirmRecord() {
        super(TOrderBillConfirm.T_ORDER_BILL_CONFIRM);
    }

    /**
     * Create a detached, initialised TOrderBillConfirmRecord
     */
    public TOrderBillConfirmRecord(Long id, Long customerId, Integer balanceDate, Integer billMonth, Integer cutMoneyDate, String telphone, Short billStatus, String remark, Timestamp cdate, Timestamp mdate) {
        super(TOrderBillConfirm.T_ORDER_BILL_CONFIRM);

        set(0, id);
        set(1, customerId);
        set(2, balanceDate);
        set(3, billMonth);
        set(4, cutMoneyDate);
        set(5, telphone);
        set(6, billStatus);
        set(7, remark);
        set(8, cdate);
        set(9, mdate);
    }
}
