/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.tables.records;


import cn.zyj.dbexporter.jooq.tables.TOrderRentTypeChangeLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderRentTypeChangeLogRecord extends UpdatableRecordImpl<TOrderRentTypeChangeLogRecord> implements Record9<Integer, Integer, Integer, String, Integer, Integer, Long, Long, Timestamp> {

    private static final long serialVersionUID = 1252814315;

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.now_balance_num</code>.
     */
    public void setNowBalanceNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.now_balance_num</code>.
     */
    public Integer getNowBalanceNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.rent_type_id</code>.
     */
    public void setRentTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.rent_type_id</code>.
     */
    public Integer getRentTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.order_id</code>.
     */
    public void setOrderId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.order_item_id</code>.
     */
    public void setOrderItemId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.order_item_id</code>.
     */
    public Integer getOrderItemId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.item_detail_id</code>.
     */
    public void setItemDetailId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.item_detail_id</code>.
     */
    public Integer getItemDetailId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.old_rent_money</code>.
     */
    public void setOldRentMoney(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.old_rent_money</code>.
     */
    public Long getOldRentMoney() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.new_rent_money</code>.
     */
    public void setNewRentMoney(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.new_rent_money</code>.
     */
    public Long getNewRentMoney() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>db_mall.t_order_rent_type_change_log.cdate</code>.
     */
    public void setCdate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_mall.t_order_rent_type_change_log.cdate</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Integer, Integer, Long, Long, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Integer, Integer, Long, Long, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.NOW_BALANCE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.RENT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.ORDER_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.ITEM_DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.OLD_RENT_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.NEW_RENT_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG.CDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getNowBalanceNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getOrderItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getOldRentMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getNewRentMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNowBalanceNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOrderItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getItemDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getOldRentMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getNewRentMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value2(Integer value) {
        setNowBalanceNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value3(Integer value) {
        setRentTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value4(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value5(Integer value) {
        setOrderItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value6(Integer value) {
        setItemDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value7(Long value) {
        setOldRentMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value8(Long value) {
        setNewRentMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord value9(Timestamp value) {
        setCdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderRentTypeChangeLogRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, Long value7, Long value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOrderRentTypeChangeLogRecord
     */
    public TOrderRentTypeChangeLogRecord() {
        super(TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG);
    }

    /**
     * Create a detached, initialised TOrderRentTypeChangeLogRecord
     */
    public TOrderRentTypeChangeLogRecord(Integer id, Integer nowBalanceNum, Integer rentTypeId, String orderId, Integer orderItemId, Integer itemDetailId, Long oldRentMoney, Long newRentMoney, Timestamp cdate) {
        super(TOrderRentTypeChangeLog.T_ORDER_RENT_TYPE_CHANGE_LOG);

        set(0, id);
        set(1, nowBalanceNum);
        set(2, rentTypeId);
        set(3, orderId);
        set(4, orderItemId);
        set(5, itemDetailId);
        set(6, oldRentMoney);
        set(7, newRentMoney);
        set(8, cdate);
    }
}
