/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.records;


import cn.zyj.dbexporter.jooq.db_mall.tables.TAccessControlLog;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccessControlLogRecord extends UpdatableRecordImpl<TAccessControlLogRecord> implements Record7<Integer, String, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1754716733;

    /**
     * Setter for <code>db_mall.t_access_control_log.id</code>.
     */
    public TAccessControlLogRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.key_str</code>.
     */
    public TAccessControlLogRecord setKeyStr(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.key_str</code>.
     */
    @Size(max = 180)
    public String getKeyStr() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.request_str</code>.
     */
    public TAccessControlLogRecord setRequestStr(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.request_str</code>.
     */
    @Size(max = 65535)
    public String getRequestStr() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.response_str</code>.
     */
    public TAccessControlLogRecord setResponseStr(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.response_str</code>.
     */
    @Size(max = 65535)
    public String getResponseStr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.use_time</code>.
     */
    public TAccessControlLogRecord setUseTime(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.use_time</code>.
     */
    public Integer getUseTime() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.cdate</code>.
     */
    public TAccessControlLogRecord setCdate(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.cdate</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>db_mall.t_access_control_log.mdate</code>.
     */
    public TAccessControlLogRecord setMdate(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_access_control_log.mdate</code>.
     */
    public Timestamp getMdate() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.KEY_STR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.REQUEST_STR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.RESPONSE_STR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.USE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.CDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TAccessControlLog.T_ACCESS_CONTROL_LOG.MDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKeyStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRequestStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getResponseStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKeyStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRequestStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getResponseStr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getMdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value2(String value) {
        setKeyStr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value3(String value) {
        setRequestStr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value4(String value) {
        setResponseStr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value5(Integer value) {
        setUseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value6(Timestamp value) {
        setCdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord value7(Timestamp value) {
        setMdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccessControlLogRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccessControlLogRecord
     */
    public TAccessControlLogRecord() {
        super(TAccessControlLog.T_ACCESS_CONTROL_LOG);
    }

    /**
     * Create a detached, initialised TAccessControlLogRecord
     */
    public TAccessControlLogRecord(Integer id, String keyStr, String requestStr, String responseStr, Integer useTime, Timestamp cdate, Timestamp mdate) {
        super(TAccessControlLog.T_ACCESS_CONTROL_LOG);

        set(0, id);
        set(1, keyStr);
        set(2, requestStr);
        set(3, responseStr);
        set(4, useTime);
        set(5, cdate);
        set(6, mdate);
    }
}
