/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.records;


import cn.zyj.dbexporter.jooq.db_mall.tables.TSmsTemplate;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSmsTemplateRecord extends UpdatableRecordImpl<TSmsTemplateRecord> implements Record3<Integer, String, Boolean> {

    private static final long serialVersionUID = 46674068;

    /**
     * Setter for <code>db_mall.t_sms_template.id</code>.
     */
    public TSmsTemplateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_sms_template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_mall.t_sms_template.content</code>.
     */
    public TSmsTemplateRecord setContent(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_sms_template.content</code>.
     */
    @Size(max = 500)
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_mall.t_sms_template.enable</code>.
     */
    public TSmsTemplateRecord setEnable(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>db_mall.t_sms_template.enable</code>.
     */
    public Boolean getEnable() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TSmsTemplate.T_SMS_TEMPLATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TSmsTemplate.T_SMS_TEMPLATE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return TSmsTemplate.T_SMS_TEMPLATE.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSmsTemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSmsTemplateRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSmsTemplateRecord value3(Boolean value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSmsTemplateRecord values(Integer value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSmsTemplateRecord
     */
    public TSmsTemplateRecord() {
        super(TSmsTemplate.T_SMS_TEMPLATE);
    }

    /**
     * Create a detached, initialised TSmsTemplateRecord
     */
    public TSmsTemplateRecord(Integer id, String content, Boolean enable) {
        super(TSmsTemplate.T_SMS_TEMPLATE);

        set(0, id);
        set(1, content);
        set(2, enable);
    }
}
