/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_calculator.tables.records;


import cn.zyj.dbexporter.jooq.db_calculator.tables.TResource;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 资源池
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TResourceRecord extends UpdatableRecordImpl<TResourceRecord> {

    private static final long serialVersionUID = -216518714;

    /**
     * Setter for <code>db_calculator.t_resource.id</code>.
     */
    public TResourceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_calculator.t_resource.sku</code>. sku
     */
    public TResourceRecord setSku(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.sku</code>. sku
     */
    @Size(max = 300)
    public String getSku() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_calculator.t_resource.rent_or_sale</code>. 租售属性 1-租，2-售，3-租售均可
     */
    public TResourceRecord setRentOrSale(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.rent_or_sale</code>. 租售属性 1-租，2-售，3-租售均可
     */
    public Byte getRentOrSale() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>db_calculator.t_resource.rent_or_sale_status</code>. 0-正常，1-租售属性待更新
     */
    public TResourceRecord setRentOrSaleStatus(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.rent_or_sale_status</code>. 0-正常，1-租售属性待更新
     */
    public Byte getRentOrSaleStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>db_calculator.t_resource.purchase_price</code>. 采购价格
     */
    public TResourceRecord setPurchasePrice(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.purchase_price</code>. 采购价格
     */
    public BigDecimal getPurchasePrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>db_calculator.t_resource.deposit</code>. 押金
     */
    public TResourceRecord setDeposit(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.deposit</code>. 押金
     */
    public BigDecimal getDeposit() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>db_calculator.t_resource.resource_type</code>. 产品池类型
     */
    public TResourceRecord setResourceType(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.resource_type</code>. 产品池类型
     */
    public Integer getResourceType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>db_calculator.t_resource.product_type</code>. 产品类型
     */
    public TResourceRecord setProductType(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.product_type</code>. 产品类型
     */
    public Integer getProductType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>db_calculator.t_resource.quality</code>. 成色
     */
    public TResourceRecord setQuality(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.quality</code>. 成色
     */
    public Integer getQuality() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>db_calculator.t_resource.brand</code>. 品牌
     */
    public TResourceRecord setBrand(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.brand</code>. 品牌
     */
    public Integer getBrand() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>db_calculator.t_resource.model</code>. 型号
     */
    public TResourceRecord setModel(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.model</code>. 型号
     */
    @Size(max = 200)
    public String getModel() {
        return (String) get(10);
    }

    /**
     * Setter for <code>db_calculator.t_resource.service_standard</code>. 服务标准
     */
    public TResourceRecord setServiceStandard(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.service_standard</code>. 服务标准
     */
    public Integer getServiceStandard() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>db_calculator.t_resource.os</code>. 操作系统
     */
    public TResourceRecord setOs(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.os</code>. 操作系统
     */
    public Integer getOs() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>db_calculator.t_resource.core_config</code>. 核心配置
     */
    public TResourceRecord setCoreConfig(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.core_config</code>. 核心配置
     */
    @Size(max = 500)
    public String getCoreConfig() {
        return (String) get(13);
    }

    /**
     * Setter for <code>db_calculator.t_resource.uncore_config</code>. 非核心配置
     */
    public TResourceRecord setUncoreConfig(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.uncore_config</code>. 非核心配置
     */
    @Size(max = 500)
    public String getUncoreConfig() {
        return (String) get(14);
    }

    /**
     * Setter for <code>db_calculator.t_resource.cpu_type</code>. cpu类型
     */
    public TResourceRecord setCpuType(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.cpu_type</code>. cpu类型
     */
    public Integer getCpuType() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>db_calculator.t_resource.cpu_model</code>. cpu型号
     */
    public TResourceRecord setCpuModel(Integer value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.cpu_model</code>. cpu型号
     */
    public Integer getCpuModel() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>db_calculator.t_resource.ram</code>. ram
     */
    public TResourceRecord setRam(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.ram</code>. ram
     */
    public Integer getRam() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>db_calculator.t_resource.hd1</code>. hd1
     */
    public TResourceRecord setHd1(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.hd1</code>. hd1
     */
    public Integer getHd1() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>db_calculator.t_resource.hd2</code>. hd2
     */
    public TResourceRecord setHd2(Integer value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.hd2</code>. hd2
     */
    public Integer getHd2() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>db_calculator.t_resource.gpu</code>. gpu
     */
    public TResourceRecord setGpu(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.gpu</code>. gpu
     */
    public Integer getGpu() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>db_calculator.t_resource.screen_size</code>. 屏幕尺寸
     */
    public TResourceRecord setScreenSize(Integer value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.screen_size</code>. 屏幕尺寸
     */
    public Integer getScreenSize() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>db_calculator.t_resource.resolution</code>. 分辨率
     */
    public TResourceRecord setResolution(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.resolution</code>. 分辨率
     */
    public Integer getResolution() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>db_calculator.t_resource.arrival_cycle</code>. 到货周期
     */
    public TResourceRecord setArrivalCycle(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.arrival_cycle</code>. 到货周期
     */
    @Size(max = 200)
    public String getArrivalCycle() {
        return (String) get(23);
    }

    /**
     * Setter for <code>db_calculator.t_resource.offer_validity</code>. 报价有效期
     */
    public TResourceRecord setOfferValidity(Integer value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.offer_validity</code>. 报价有效期
     */
    public Integer getOfferValidity() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>db_calculator.t_resource.cdate</code>.
     */
    public TResourceRecord setCdate(Timestamp value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.cdate</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>db_calculator.t_resource.mdate</code>.
     */
    public TResourceRecord setMdate(Timestamp value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.mdate</code>.
     */
    public Timestamp getMdate() {
        return (Timestamp) get(26);
    }

    /**
     * Setter for <code>db_calculator.t_resource.creater_id</code>. 创建人ID
     */
    public TResourceRecord setCreaterId(Integer value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.creater_id</code>. 创建人ID
     */
    public Integer getCreaterId() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>db_calculator.t_resource.creater_name</code>. 创建人姓名
     */
    public TResourceRecord setCreaterName(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.creater_name</code>. 创建人姓名
     */
    @Size(max = 20)
    public String getCreaterName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>db_calculator.t_resource.data_status</code>. 状态 0:正常 -1:删除
     */
    public TResourceRecord setDataStatus(Integer value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.data_status</code>. 状态 0:正常 -1:删除
     */
    public Integer getDataStatus() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>db_calculator.t_resource.audit_status</code>. 审核状态 0:待更新 1:待审核 2:审核通过 3:审核未通过
     */
    public TResourceRecord setAuditStatus(Integer value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.audit_status</code>. 审核状态 0:待更新 1:待审核 2:审核通过 3:审核未通过
     */
    public Integer getAuditStatus() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>db_calculator.t_resource.is_overlimit</code>. 是否偏移超限 0:未超限 1:超限
     */
    public TResourceRecord setIsOverlimit(Integer value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.is_overlimit</code>. 是否偏移超限 0:未超限 1:超限
     */
    public Integer getIsOverlimit() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>db_calculator.t_resource.update_user_id</code>. 最后更新人id
     */
    public TResourceRecord setUpdateUserId(Integer value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.update_user_id</code>. 最后更新人id
     */
    public Integer getUpdateUserId() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>db_calculator.t_resource.update_user_name</code>. 最后更新人姓名
     */
    public TResourceRecord setUpdateUserName(String value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.update_user_name</code>. 最后更新人姓名
     */
    @Size(max = 20)
    public String getUpdateUserName() {
        return (String) get(33);
    }

    /**
     * Setter for <code>db_calculator.t_resource.expected_arrival_date</code>. 期望到货时间
     */
    public TResourceRecord setExpectedArrivalDate(String value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.expected_arrival_date</code>. 期望到货时间
     */
    @Size(max = 200)
    public String getExpectedArrivalDate() {
        return (String) get(34);
    }

    /**
     * Setter for <code>db_calculator.t_resource.tender_status</code>. 是否为投标项目 0:否 1:是
     */
    public TResourceRecord setTenderStatus(Integer value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.tender_status</code>. 是否为投标项目 0:否 1:是
     */
    public Integer getTenderStatus() {
        return (Integer) get(35);
    }

    /**
     * Setter for <code>db_calculator.t_resource.delivery_city</code>. 到货城市
     */
    public TResourceRecord setDeliveryCity(String value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.delivery_city</code>. 到货城市
     */
    @Size(max = 100)
    public String getDeliveryCity() {
        return (String) get(36);
    }

    /**
     * Setter for <code>db_calculator.t_resource.supply_status</code>. 货源情况
     */
    public TResourceRecord setSupplyStatus(Integer value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.supply_status</code>. 货源情况
     */
    public Integer getSupplyStatus() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>db_calculator.t_resource.include_install_cost</code>. 是否包含安装费 0:否 1:是
     */
    public TResourceRecord setIncludeInstallCost(Integer value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.include_install_cost</code>. 是否包含安装费 0:否 1:是
     */
    public Integer getIncludeInstallCost() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>db_calculator.t_resource.update_remark</code>. 更新备注
     */
    public TResourceRecord setUpdateRemark(String value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.update_remark</code>. 更新备注
     */
    @Size(max = 500)
    public String getUpdateRemark() {
        return (String) get(39);
    }

    /**
     * Setter for <code>db_calculator.t_resource.article_no</code>. 货号
     */
    public TResourceRecord setArticleNo(String value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.article_no</code>. 货号
     */
    @Size(max = 200)
    public String getArticleNo() {
        return (String) get(40);
    }

    /**
     * Setter for <code>db_calculator.t_resource.spu</code>. spu
     */
    public TResourceRecord setSpu(String value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.spu</code>. spu
     */
    @Size(max = 300)
    public String getSpu() {
        return (String) get(41);
    }

    /**
     * Setter for <code>db_calculator.t_resource.is_group</code>. 是否为组合sku 0:否 1:是
     */
    public TResourceRecord setIsGroup(Integer value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for <code>db_calculator.t_resource.is_group</code>. 是否为组合sku 0:否 1:是
     */
    public Integer getIsGroup() {
        return (Integer) get(42);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TResourceRecord
     */
    public TResourceRecord() {
        super(TResource.T_RESOURCE);
    }

    /**
     * Create a detached, initialised TResourceRecord
     */
    public TResourceRecord(Integer id, String sku, Byte rentOrSale, Byte rentOrSaleStatus, BigDecimal purchasePrice, BigDecimal deposit, Integer resourceType, Integer productType, Integer quality, Integer brand, String model, Integer serviceStandard, Integer os, String coreConfig, String uncoreConfig, Integer cpuType, Integer cpuModel, Integer ram, Integer hd1, Integer hd2, Integer gpu, Integer screenSize, Integer resolution, String arrivalCycle, Integer offerValidity, Timestamp cdate, Timestamp mdate, Integer createrId, String createrName, Integer dataStatus, Integer auditStatus, Integer isOverlimit, Integer updateUserId, String updateUserName, String expectedArrivalDate, Integer tenderStatus, String deliveryCity, Integer supplyStatus, Integer includeInstallCost, String updateRemark, String articleNo, String spu, Integer isGroup) {
        super(TResource.T_RESOURCE);

        set(0, id);
        set(1, sku);
        set(2, rentOrSale);
        set(3, rentOrSaleStatus);
        set(4, purchasePrice);
        set(5, deposit);
        set(6, resourceType);
        set(7, productType);
        set(8, quality);
        set(9, brand);
        set(10, model);
        set(11, serviceStandard);
        set(12, os);
        set(13, coreConfig);
        set(14, uncoreConfig);
        set(15, cpuType);
        set(16, cpuModel);
        set(17, ram);
        set(18, hd1);
        set(19, hd2);
        set(20, gpu);
        set(21, screenSize);
        set(22, resolution);
        set(23, arrivalCycle);
        set(24, offerValidity);
        set(25, cdate);
        set(26, mdate);
        set(27, createrId);
        set(28, createrName);
        set(29, dataStatus);
        set(30, auditStatus);
        set(31, isOverlimit);
        set(32, updateUserId);
        set(33, updateUserName);
        set(34, expectedArrivalDate);
        set(35, tenderStatus);
        set(36, deliveryCity);
        set(37, supplyStatus);
        set(38, includeInstallCost);
        set(39, updateRemark);
        set(40, articleNo);
        set(41, spu);
        set(42, isGroup);
    }
}
