/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables;


import cn.zyj.dbexporter.jooq.db_mall.DbMall;
import cn.zyj.dbexporter.jooq.db_mall.Indexes;
import cn.zyj.dbexporter.jooq.db_mall.Keys;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TCartsLogsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCartsLogs extends TableImpl<TCartsLogsRecord> {

    private static final long serialVersionUID = -643643871;

    /**
     * The reference instance of <code>db_mall.t_carts_logs</code>
     */
    public static final TCartsLogs T_CARTS_LOGS = new TCartsLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TCartsLogsRecord> getRecordType() {
        return TCartsLogsRecord.class;
    }

    /**
     * The column <code>db_mall.t_carts_logs.id</code>.
     */
    public final TableField<TCartsLogsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.product_id</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.num</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.status</code>.
     */
    public final TableField<TCartsLogsRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.customer_id</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.rent_type</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> RENT_TYPE = createField("rent_type", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.start_date</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db_mall.t_carts_logs.month</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> MONTH = createField("month", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db_mall.t_carts_logs.is_sale</code>.
     */
    public final TableField<TCartsLogsRecord, Byte> IS_SALE = createField("is_sale", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.insurance_type_id</code>.
     */
    public final TableField<TCartsLogsRecord, Byte> INSURANCE_TYPE_ID = createField("insurance_type_id", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>db_mall.t_carts_logs.ip</code>.
     */
    public final TableField<TCartsLogsRecord, Long> IP = createField("ip", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.user_agent</code>.
     */
    public final TableField<TCartsLogsRecord, String> USER_AGENT = createField("user_agent", org.jooq.impl.SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.source</code>.
     */
    public final TableField<TCartsLogsRecord, Byte> SOURCE = createField("source", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.is_checked</code>.
     */
    public final TableField<TCartsLogsRecord, Byte> IS_CHECKED = createField("is_checked", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.service_id</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.cdate</code>.
     */
    public final TableField<TCartsLogsRecord, Timestamp> CDATE = createField("cdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.mdate</code>.
     */
    public final TableField<TCartsLogsRecord, Timestamp> MDATE = createField("mdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_carts_logs.rent_type_id</code>.
     */
    public final TableField<TCartsLogsRecord, Integer> RENT_TYPE_ID = createField("rent_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>db_mall.t_carts_logs</code> table reference
     */
    public TCartsLogs() {
        this(DSL.name("t_carts_logs"), null);
    }

    /**
     * Create an aliased <code>db_mall.t_carts_logs</code> table reference
     */
    public TCartsLogs(String alias) {
        this(DSL.name(alias), T_CARTS_LOGS);
    }

    /**
     * Create an aliased <code>db_mall.t_carts_logs</code> table reference
     */
    public TCartsLogs(Name alias) {
        this(alias, T_CARTS_LOGS);
    }

    private TCartsLogs(Name alias, Table<TCartsLogsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TCartsLogs(Name alias, Table<TCartsLogsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TCartsLogs(Table<O> child, ForeignKey<O, TCartsLogsRecord> key) {
        super(child, key, T_CARTS_LOGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMall.DB_MALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_CARTS_LOGS_CUSTOMER_ID_STATUS, Indexes.T_CARTS_LOGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TCartsLogsRecord, Long> getIdentity() {
        return Keys.IDENTITY_T_CARTS_LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TCartsLogsRecord> getPrimaryKey() {
        return Keys.KEY_T_CARTS_LOGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TCartsLogsRecord>> getKeys() {
        return Arrays.<UniqueKey<TCartsLogsRecord>>asList(Keys.KEY_T_CARTS_LOGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCartsLogs as(String alias) {
        return new TCartsLogs(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCartsLogs as(Name alias) {
        return new TCartsLogs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TCartsLogs rename(String name) {
        return new TCartsLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TCartsLogs rename(Name name) {
        return new TCartsLogs(name, null);
    }
}
