/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables;


import cn.zyj.dbexporter.jooq.db_mall.DbMall;
import cn.zyj.dbexporter.jooq.db_mall.Indexes;
import cn.zyj.dbexporter.jooq.db_mall.Keys;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TInvoiceDetailRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInvoiceDetail extends TableImpl<TInvoiceDetailRecord> {

    private static final long serialVersionUID = -982279774;

    /**
     * The reference instance of <code>db_mall.t_invoice_detail</code>
     */
    public static final TInvoiceDetail T_INVOICE_DETAIL = new TInvoiceDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TInvoiceDetailRecord> getRecordType() {
        return TInvoiceDetailRecord.class;
    }

    /**
     * The column <code>db_mall.t_invoice_detail.id</code>.
     */
    public final TableField<TInvoiceDetailRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>db_mall.t_invoice_detail.finance_invoice_id</code>. 财务发票Id
     */
    public final TableField<TInvoiceDetailRecord, Integer> FINANCE_INVOICE_ID = createField("finance_invoice_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "财务发票Id");

    /**
     * The column <code>db_mall.t_invoice_detail.request_id</code>. 商城发票申请id
     */
    public final TableField<TInvoiceDetailRecord, Integer> REQUEST_ID = createField("request_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "商城发票申请id");

    /**
     * The column <code>db_mall.t_invoice_detail.status</code>. 发票状态（0已开票，1作废，2被红冲，3红冲）
     */
    public final TableField<TInvoiceDetailRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "发票状态（0已开票，1作废，2被红冲，3红冲）");

    /**
     * The column <code>db_mall.t_invoice_detail.invoice_type</code>. 发票种类（1普票，2专票 3，电票）
     */
    public final TableField<TInvoiceDetailRecord, Byte> INVOICE_TYPE = createField("invoice_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "发票种类（1普票，2专票 3，电票）");

    /**
     * The column <code>db_mall.t_invoice_detail.amount</code>. 发票金额

     */
    public final TableField<TInvoiceDetailRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "发票金额\r\n");

    /**
     * The column <code>db_mall.t_invoice_detail.exe_status</code>. 发票执行状态（1未开票 2部分开票 3全部开票）
     */
    public final TableField<TInvoiceDetailRecord, Integer> EXE_STATUS = createField("exe_status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "发票执行状态（1未开票 2部分开票 3全部开票）");

    /**
     * The column <code>db_mall.t_invoice_detail.invoice_no</code>. 发票号（电子发票必填）
     */
    public final TableField<TInvoiceDetailRecord, String> INVOICE_NO = createField("invoice_no", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "发票号（电子发票必填）");

    /**
     * The column <code>db_mall.t_invoice_detail.invoice_code</code>. 百旺发票代码（电子发票必填）
     */
    public final TableField<TInvoiceDetailRecord, String> INVOICE_CODE = createField("invoice_code", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "百旺发票代码（电子发票必填）");

    /**
     * The column <code>db_mall.t_invoice_detail.invoice_date</code>. 开票时间
     */
    public final TableField<TInvoiceDetailRecord, Timestamp> INVOICE_DATE = createField("invoice_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "开票时间");

    /**
     * The column <code>db_mall.t_invoice_detail.path</code>. 百旺发票地址
     */
    public final TableField<TInvoiceDetailRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR(300).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "百旺发票地址");

    /**
     * The column <code>db_mall.t_invoice_detail.cdate</code>.
     */
    public final TableField<TInvoiceDetailRecord, Timestamp> CDATE = createField("cdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_invoice_detail.mdate</code>.
     */
    public final TableField<TInvoiceDetailRecord, Timestamp> MDATE = createField("mdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>db_mall.t_invoice_detail</code> table reference
     */
    public TInvoiceDetail() {
        this(DSL.name("t_invoice_detail"), null);
    }

    /**
     * Create an aliased <code>db_mall.t_invoice_detail</code> table reference
     */
    public TInvoiceDetail(String alias) {
        this(DSL.name(alias), T_INVOICE_DETAIL);
    }

    /**
     * Create an aliased <code>db_mall.t_invoice_detail</code> table reference
     */
    public TInvoiceDetail(Name alias) {
        this(alias, T_INVOICE_DETAIL);
    }

    private TInvoiceDetail(Name alias, Table<TInvoiceDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private TInvoiceDetail(Name alias, Table<TInvoiceDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TInvoiceDetail(Table<O> child, ForeignKey<O, TInvoiceDetailRecord> key) {
        super(child, key, T_INVOICE_DETAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMall.DB_MALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_INVOICE_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TInvoiceDetailRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_INVOICE_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TInvoiceDetailRecord> getPrimaryKey() {
        return Keys.KEY_T_INVOICE_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TInvoiceDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<TInvoiceDetailRecord>>asList(Keys.KEY_T_INVOICE_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInvoiceDetail as(String alias) {
        return new TInvoiceDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInvoiceDetail as(Name alias) {
        return new TInvoiceDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TInvoiceDetail rename(String name) {
        return new TInvoiceDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TInvoiceDetail rename(Name name) {
        return new TInvoiceDetail(name, null);
    }
}
