/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables;


import cn.zyj.dbexporter.jooq.db_mall.DbMall;
import cn.zyj.dbexporter.jooq.db_mall.Indexes;
import cn.zyj.dbexporter.jooq.db_mall.Keys;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TProductSkuidInfoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProductSkuidInfo extends TableImpl<TProductSkuidInfoRecord> {

    private static final long serialVersionUID = -350678916;

    /**
     * The reference instance of <code>db_mall.t_product_skuid_info</code>
     */
    public static final TProductSkuidInfo T_PRODUCT_SKUID_INFO = new TProductSkuidInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProductSkuidInfoRecord> getRecordType() {
        return TProductSkuidInfoRecord.class;
    }

    /**
     * The column <code>db_mall.t_product_skuid_info.id</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.product_id</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Integer> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.sku_id</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Integer> SKU_ID = createField("sku_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.stock</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Integer> STOCK = createField("stock", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.real_stock</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Integer> REAL_STOCK = createField("real_stock", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.is_presale</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Byte> IS_PRESALE = createField("is_presale", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.sync_status</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Byte> SYNC_STATUS = createField("sync_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.rents</code>.
     */
    public final TableField<TProductSkuidInfoRecord, String> RENTS = createField("rents", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.cdate</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Timestamp> CDATE = createField("cdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>db_mall.t_product_skuid_info.mdate</code>.
     */
    public final TableField<TProductSkuidInfoRecord, Timestamp> MDATE = createField("mdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>db_mall.t_product_skuid_info</code> table reference
     */
    public TProductSkuidInfo() {
        this(DSL.name("t_product_skuid_info"), null);
    }

    /**
     * Create an aliased <code>db_mall.t_product_skuid_info</code> table reference
     */
    public TProductSkuidInfo(String alias) {
        this(DSL.name(alias), T_PRODUCT_SKUID_INFO);
    }

    /**
     * Create an aliased <code>db_mall.t_product_skuid_info</code> table reference
     */
    public TProductSkuidInfo(Name alias) {
        this(alias, T_PRODUCT_SKUID_INFO);
    }

    private TProductSkuidInfo(Name alias, Table<TProductSkuidInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TProductSkuidInfo(Name alias, Table<TProductSkuidInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TProductSkuidInfo(Table<O> child, ForeignKey<O, TProductSkuidInfoRecord> key) {
        super(child, key, T_PRODUCT_SKUID_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMall.DB_MALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_PRODUCT_SKUID_INFO_PRIMARY, Indexes.T_PRODUCT_SKUID_INFO_PRODUCT_ID_STOCK, Indexes.T_PRODUCT_SKUID_INFO_SKU_ID, Indexes.T_PRODUCT_SKUID_INFO_SYNC_STATUS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TProductSkuidInfoRecord, Long> getIdentity() {
        return Keys.IDENTITY_T_PRODUCT_SKUID_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TProductSkuidInfoRecord> getPrimaryKey() {
        return Keys.KEY_T_PRODUCT_SKUID_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TProductSkuidInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TProductSkuidInfoRecord>>asList(Keys.KEY_T_PRODUCT_SKUID_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProductSkuidInfo as(String alias) {
        return new TProductSkuidInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProductSkuidInfo as(Name alias) {
        return new TProductSkuidInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TProductSkuidInfo rename(String name) {
        return new TProductSkuidInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProductSkuidInfo rename(Name name) {
        return new TProductSkuidInfo(name, null);
    }
}
