/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables;


import cn.zyj.dbexporter.jooq.db_mall.DbMall;
import cn.zyj.dbexporter.jooq.db_mall.Indexes;
import cn.zyj.dbexporter.jooq.db_mall.Keys;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TTestUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTestUser extends TableImpl<TTestUserRecord> {

    private static final long serialVersionUID = 638158782;

    /**
     * The reference instance of <code>db_mall.t_test_user</code>
     */
    public static final TTestUser T_TEST_USER = new TTestUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTestUserRecord> getRecordType() {
        return TTestUserRecord.class;
    }

    /**
     * The column <code>db_mall.t_test_user.id</code>.
     */
    public final TableField<TTestUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>db_mall.t_test_user.phone</code>.
     */
    public final TableField<TTestUserRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>db_mall.t_test_user.name</code>.
     */
    public final TableField<TTestUserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>db_mall.t_test_user.company</code>.
     */
    public final TableField<TTestUserRecord, String> COMPANY = createField("company", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>db_mall.t_test_user</code> table reference
     */
    public TTestUser() {
        this(DSL.name("t_test_user"), null);
    }

    /**
     * Create an aliased <code>db_mall.t_test_user</code> table reference
     */
    public TTestUser(String alias) {
        this(DSL.name(alias), T_TEST_USER);
    }

    /**
     * Create an aliased <code>db_mall.t_test_user</code> table reference
     */
    public TTestUser(Name alias) {
        this(alias, T_TEST_USER);
    }

    private TTestUser(Name alias, Table<TTestUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TTestUser(Name alias, Table<TTestUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TTestUser(Table<O> child, ForeignKey<O, TTestUserRecord> key) {
        super(child, key, T_TEST_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMall.DB_MALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_TEST_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TTestUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_TEST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TTestUserRecord> getPrimaryKey() {
        return Keys.KEY_T_TEST_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TTestUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TTestUserRecord>>asList(Keys.KEY_T_TEST_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTestUser as(String alias) {
        return new TTestUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTestUser as(Name alias) {
        return new TTestUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTestUser rename(String name) {
        return new TTestUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTestUser rename(Name name) {
        return new TTestUser(name, null);
    }
}
