/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.AssetsReceiver;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.AssetsReceiverRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetsReceiverDao extends DAOImpl<AssetsReceiverRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver, Long> {

    /**
     * Create a new AssetsReceiverDao without any configuration
     */
    public AssetsReceiverDao() {
        super(AssetsReceiver.ASSETS_RECEIVER, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver.class);
    }

    /**
     * Create a new AssetsReceiverDao with an attached configuration
     */
    public AssetsReceiverDao(Configuration configuration) {
        super(AssetsReceiver.ASSETS_RECEIVER, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchById(Long... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver fetchOneById(Long value) {
        return fetchOne(AssetsReceiver.ASSETS_RECEIVER.ID, value);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByCustomerId(Long... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByName(String... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.NAME, values);
    }

    /**
     * Fetch records that have <code>primary_sector IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByPrimarySector(String... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.PRIMARY_SECTOR, values);
    }

    /**
     * Fetch records that have <code>secondary_sector IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchBySecondarySector(String... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.SECONDARY_SECTOR, values);
    }

    /**
     * Fetch records that have <code>company_name IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByCompanyName(String... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.COMPANY_NAME, values);
    }

    /**
     * Fetch records that have <code>office_address IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByOfficeAddress(String... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.OFFICE_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>cdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByCdate(Timestamp... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.CDATE, values);
    }

    /**
     * Fetch records that have <code>mdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.AssetsReceiver> fetchByMdate(Timestamp... values) {
        return fetch(AssetsReceiver.ASSETS_RECEIVER.MDATE, values);
    }
}
