/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TAssetsPackages;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TAssetsPackagesRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAssetsPackagesDao extends DAOImpl<TAssetsPackagesRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages, Integer> {

    /**
     * Create a new TAssetsPackagesDao without any configuration
     */
    public TAssetsPackagesDao() {
        super(TAssetsPackages.T_ASSETS_PACKAGES, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages.class);
    }

    /**
     * Create a new TAssetsPackagesDao with an attached configuration
     */
    public TAssetsPackagesDao(Configuration configuration) {
        super(TAssetsPackages.T_ASSETS_PACKAGES, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchById(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages fetchOneById(Integer value) {
        return fetchOne(TAssetsPackages.T_ASSETS_PACKAGES.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByName(String... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.NAME, values);
    }

    /**
     * Fetch records that have <code>platform_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByPlatformId(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.PLATFORM_ID, values);
    }

    /**
     * Fetch records that have <code>type_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByTypeId(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>sell_money IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchBySellMoney(String... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.SELL_MONEY, values);
    }

    /**
     * Fetch records that have <code>fee IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByFee(BigDecimal... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.FEE, values);
    }

    /**
     * Fetch records that have <code>interest IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByInterest(BigDecimal... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.INTEREST, values);
    }

    /**
     * Fetch records that have <code>repayment_date IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByRepaymentDate(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.REPAYMENT_DATE, values);
    }

    /**
     * Fetch records that have <code>self_repayment_date IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchBySelfRepaymentDate(Date... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.SELF_REPAYMENT_DATE, values);
    }

    /**
     * Fetch records that have <code>repayment_amount IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByRepaymentAmount(BigDecimal... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.REPAYMENT_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>month IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByMonth(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.MONTH, values);
    }

    /**
     * Fetch records that have <code>give_money_date IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByGiveMoneyDate(Date... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.GIVE_MONEY_DATE, values);
    }

    /**
     * Fetch records that have <code>hand_money IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByHandMoney(BigDecimal... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.HAND_MONEY, values);
    }

    /**
     * Fetch records that have <code>company_num IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByCompanyNum(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.COMPANY_NUM, values);
    }

    /**
     * Fetch records that have <code>device_num IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByDeviceNum(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.DEVICE_NUM, values);
    }

    /**
     * Fetch records that have <code>deposit IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByDeposit(BigDecimal... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.DEPOSIT, values);
    }

    /**
     * Fetch records that have <code>manager_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByManagerId(Integer... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.MANAGER_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByStatus(Byte... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.STATUS, values);
    }

    /**
     * Fetch records that have <code>buy_num IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByBuyNum(String... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.BUY_NUM, values);
    }

    /**
     * Fetch records that have <code>cdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByCdate(Timestamp... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.CDATE, values);
    }

    /**
     * Fetch records that have <code>mdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TAssetsPackages> fetchByMdate(Timestamp... values) {
        return fetch(TAssetsPackages.T_ASSETS_PACKAGES.MDATE, values);
    }
}
