/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TCustomerWithdraw;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TCustomerWithdrawRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCustomerWithdrawDao extends DAOImpl<TCustomerWithdrawRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw, Long> {

    /**
     * Create a new TCustomerWithdrawDao without any configuration
     */
    public TCustomerWithdrawDao() {
        super(TCustomerWithdraw.T_CUSTOMER_WITHDRAW, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw.class);
    }

    /**
     * Create a new TCustomerWithdrawDao with an attached configuration
     */
    public TCustomerWithdrawDao(Configuration configuration) {
        super(TCustomerWithdraw.T_CUSTOMER_WITHDRAW, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchById(Long... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw fetchOneById(Long value) {
        return fetchOne(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.ID, value);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByCustomerId(Integer... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByAmount(BigDecimal... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByIp(Long... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.IP, values);
    }

    /**
     * Fetch records that have <code>user_agent IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByUserAgent(String... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.USER_AGENT, values);
    }

    /**
     * Fetch records that have <code>type_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByTypeId(Byte... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>account IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByAccount(String... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByName(String... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.NAME, values);
    }

    /**
     * Fetch records that have <code>check_manager_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByCheckManagerId(Integer... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.CHECK_MANAGER_ID, values);
    }

    /**
     * Fetch records that have <code>check_time IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByCheckTime(Timestamp... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.CHECK_TIME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByStatus(Integer... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.STATUS, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByRemark(String... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.REMARK, values);
    }

    /**
     * Fetch records that have <code>cdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByCdate(Timestamp... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.CDATE, values);
    }

    /**
     * Fetch records that have <code>mdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByMdate(Timestamp... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.MDATE, values);
    }

    /**
     * Fetch records that have <code>pay_time IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TCustomerWithdraw> fetchByPayTime(Timestamp... values) {
        return fetch(TCustomerWithdraw.T_CUSTOMER_WITHDRAW.PAY_TIME, values);
    }
}
