/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TEveryDay;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TEveryDayRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TEveryDayDao extends DAOImpl<TEveryDayRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay, Integer> {

    /**
     * Create a new TEveryDayDao without any configuration
     */
    public TEveryDayDao() {
        super(TEveryDay.T_EVERY_DAY, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay.class);
    }

    /**
     * Create a new TEveryDayDao with an attached configuration
     */
    public TEveryDayDao(Configuration configuration) {
        super(TEveryDay.T_EVERY_DAY, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay> fetchById(Integer... values) {
        return fetch(TEveryDay.T_EVERY_DAY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay fetchOneById(Integer value) {
        return fetchOne(TEveryDay.T_EVERY_DAY.ID, value);
    }

    /**
     * Fetch records that have <code>day IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay> fetchByDay(Integer... values) {
        return fetch(TEveryDay.T_EVERY_DAY.DAY, values);
    }

    /**
     * Fetch a unique record that has <code>day = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay fetchOneByDay(Integer value) {
        return fetchOne(TEveryDay.T_EVERY_DAY.DAY, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay> fetchByStatus(Byte... values) {
        return fetch(TEveryDay.T_EVERY_DAY.STATUS, values);
    }

    /**
     * Fetch records that have <code>cdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay> fetchByCdate(Timestamp... values) {
        return fetch(TEveryDay.T_EVERY_DAY.CDATE, values);
    }

    /**
     * Fetch records that have <code>mdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TEveryDay> fetchByMdate(Timestamp... values) {
        return fetch(TEveryDay.T_EVERY_DAY.MDATE, values);
    }
}
