/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TInvoiceNotice;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TInvoiceNoticeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 发票提醒文案
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInvoiceNoticeDao extends DAOImpl<TInvoiceNoticeRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice, Integer> {

    /**
     * Create a new TInvoiceNoticeDao without any configuration
     */
    public TInvoiceNoticeDao() {
        super(TInvoiceNotice.T_INVOICE_NOTICE, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice.class);
    }

    /**
     * Create a new TInvoiceNoticeDao with an attached configuration
     */
    public TInvoiceNoticeDao(Configuration configuration) {
        super(TInvoiceNotice.T_INVOICE_NOTICE, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchById(Integer... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice fetchOneById(Integer value) {
        return fetchOne(TInvoiceNotice.T_INVOICE_NOTICE.ID, value);
    }

    /**
     * Fetch records that have <code>invoice_type IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchByInvoiceType(Integer... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.INVOICE_TYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchByStatus(Integer... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.STATUS, values);
    }

    /**
     * Fetch records that have <code>message IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchByMessage(String... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.MESSAGE, values);
    }

    /**
     * Fetch records that have <code>cdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchByCdate(Timestamp... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.CDATE, values);
    }

    /**
     * Fetch records that have <code>mdate IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TInvoiceNotice> fetchByMdate(Timestamp... values) {
        return fetch(TInvoiceNotice.T_INVOICE_NOTICE.MDATE, values);
    }
}
