/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TOrderItemsDetailReturnLog;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TOrderItemsDetailReturnLogRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderItemsDetailReturnLogDao extends DAOImpl<TOrderItemsDetailReturnLogRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog, Integer> {

    /**
     * Create a new TOrderItemsDetailReturnLogDao without any configuration
     */
    public TOrderItemsDetailReturnLogDao() {
        super(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog.class);
    }

    /**
     * Create a new TOrderItemsDetailReturnLogDao with an attached configuration
     */
    public TOrderItemsDetailReturnLogDao(Configuration configuration) {
        super(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchById(Integer... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog fetchOneById(Integer value) {
        return fetchOne(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchByOrderId(String... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>item_detail_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchByItemDetailId(Integer... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.ITEM_DETAIL_ID, values);
    }

    /**
     * Fetch records that have <code>sn IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchBySn(String... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.SN, values);
    }

    /**
     * Fetch records that have <code>return_reason IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchByReturnReason(String... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.RETURN_REASON, values);
    }

    /**
     * Fetch records that have <code>op_time IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderItemsDetailReturnLog> fetchByOpTime(Timestamp... values) {
        return fetch(TOrderItemsDetailReturnLog.T_ORDER_ITEMS_DETAIL_RETURN_LOG.OP_TIME, values);
    }
}
