/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TOrderSearch;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TOrderSearchRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderSearchDao extends DAOImpl<TOrderSearchRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch, Integer> {

    /**
     * Create a new TOrderSearchDao without any configuration
     */
    public TOrderSearchDao() {
        super(TOrderSearch.T_ORDER_SEARCH, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch.class);
    }

    /**
     * Create a new TOrderSearchDao with an attached configuration
     */
    public TOrderSearchDao(Configuration configuration) {
        super(TOrderSearch.T_ORDER_SEARCH, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch> fetchById(Integer... values) {
        return fetch(TOrderSearch.T_ORDER_SEARCH.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch fetchOneById(Integer value) {
        return fetchOne(TOrderSearch.T_ORDER_SEARCH.ID, value);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch> fetchByOrderId(String... values) {
        return fetch(TOrderSearch.T_ORDER_SEARCH.ORDER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>order_id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TOrderSearch fetchOneByOrderId(String value) {
        return fetchOne(TOrderSearch.T_ORDER_SEARCH.ORDER_ID, value);
    }
}
