/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TProductMajorOtherParam;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TProductMajorOtherParamRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProductMajorOtherParamDao extends DAOImpl<TProductMajorOtherParamRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam, Integer> {

    /**
     * Create a new TProductMajorOtherParamDao without any configuration
     */
    public TProductMajorOtherParamDao() {
        super(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam.class);
    }

    /**
     * Create a new TProductMajorOtherParamDao with an attached configuration
     */
    public TProductMajorOtherParamDao(Configuration configuration) {
        super(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchById(Integer... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam fetchOneById(Integer value) {
        return fetchOne(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.ID, value);
    }

    /**
     * Fetch records that have <code>memory_capacity IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByMemoryCapacity(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.MEMORY_CAPACITY, values);
    }

    /**
     * Fetch records that have <code>disk_capacity IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByDiskCapacity(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.DISK_CAPACITY, values);
    }

    /**
     * Fetch records that have <code>disk_type IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByDiskType(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.DISK_TYPE, values);
    }

    /**
     * Fetch records that have <code>graphics_card_model IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByGraphicsCardModel(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.GRAPHICS_CARD_MODEL, values);
    }

    /**
     * Fetch records that have <code>graphics_card_type IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByGraphicsCardType(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.GRAPHICS_CARD_TYPE, values);
    }

    /**
     * Fetch records that have <code>graphics_card_capacity IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TProductMajorOtherParam> fetchByGraphicsCardCapacity(String... values) {
        return fetch(TProductMajorOtherParam.T_PRODUCT_MAJOR_OTHER_PARAM.GRAPHICS_CARD_CAPACITY, values);
    }
}
