/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.daos;


import cn.zyj.dbexporter.jooq.db_mall.tables.TRight;
import cn.zyj.dbexporter.jooq.db_mall.tables.records.TRightRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRightDao extends DAOImpl<TRightRecord, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight, Long> {

    /**
     * Create a new TRightDao without any configuration
     */
    public TRightDao() {
        super(TRight.T_RIGHT, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight.class);
    }

    /**
     * Create a new TRightDao with an attached configuration
     */
    public TRightDao(Configuration configuration) {
        super(TRight.T_RIGHT, cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight> fetchById(Long... values) {
        return fetch(TRight.T_RIGHT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight fetchOneById(Long value) {
        return fetchOne(TRight.T_RIGHT.ID, value);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight> fetchByMenuId(Long... values) {
        return fetch(TRight.T_RIGHT.MENU_ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight> fetchByName(String... values) {
        return fetch(TRight.T_RIGHT.NAME, values);
    }

    /**
     * Fetch records that have <code>href IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight> fetchByHref(String... values) {
        return fetch(TRight.T_RIGHT.HREF, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<cn.zyj.dbexporter.jooq.db_mall.tables.pojos.TRight> fetchByDescription(String... values) {
        return fetch(TRight.T_RIGHT.DESCRIPTION, values);
    }
}
