/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBillCrm implements Serializable {

    private static final long serialVersionUID = 1268057076;

    private Long   ecmId;
    private String firstTime;

    public TBillCrm() {}

    public TBillCrm(TBillCrm value) {
        this.ecmId = value.ecmId;
        this.firstTime = value.firstTime;
    }

    public TBillCrm(
        Long   ecmId,
        String firstTime
    ) {
        this.ecmId = ecmId;
        this.firstTime = firstTime;
    }

    public Long getEcmId() {
        return this.ecmId;
    }

    public TBillCrm setEcmId(Long ecmId) {
        this.ecmId = ecmId;
        return this;
    }

    @Size(max = 255)
    public String getFirstTime() {
        return this.firstTime;
    }

    public TBillCrm setFirstTime(String firstTime) {
        this.firstTime = firstTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBillCrm (");

        sb.append(ecmId);
        sb.append(", ").append(firstTime);

        sb.append(")");
        return sb.toString();
    }
}
