/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBillCheckStart implements Serializable {

    private static final long serialVersionUID = -1478985798;

    private Integer id;
    private Long    timestamp;
    private Byte    status;

    public TBillCheckStart() {}

    public TBillCheckStart(TBillCheckStart value) {
        this.id = value.id;
        this.timestamp = value.timestamp;
        this.status = value.status;
    }

    public TBillCheckStart(
        Integer id,
        Long    timestamp,
        Byte    status
    ) {
        this.id = id;
        this.timestamp = timestamp;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public TBillCheckStart setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Long getTimestamp() {
        return this.timestamp;
    }

    public TBillCheckStart setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TBillCheckStart setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBillCheckStart (");

        sb.append(id);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
