/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCustomerSay implements Serializable {

    private static final long serialVersionUID = 1028703829;

    private Integer   id;
    private String    name;
    private String    logo;
    private String    description;
    private String    products;
    private String    content;
    private Integer   oid;
    private Timestamp cdate;
    private Timestamp mdate;

    public TCustomerSay() {}

    public TCustomerSay(TCustomerSay value) {
        this.id = value.id;
        this.name = value.name;
        this.logo = value.logo;
        this.description = value.description;
        this.products = value.products;
        this.content = value.content;
        this.oid = value.oid;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TCustomerSay(
        Integer   id,
        String    name,
        String    logo,
        String    description,
        String    products,
        String    content,
        Integer   oid,
        Timestamp cdate,
        Timestamp mdate
    ) {
        this.id = id;
        this.name = name;
        this.logo = logo;
        this.description = description;
        this.products = products;
        this.content = content;
        this.oid = oid;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    public Integer getId() {
        return this.id;
    }

    public TCustomerSay setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 300)
    public String getName() {
        return this.name;
    }

    public TCustomerSay setName(String name) {
        this.name = name;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getLogo() {
        return this.logo;
    }

    public TCustomerSay setLogo(String logo) {
        this.logo = logo;
        return this;
    }

    @NotNull
    @Size(max = 1000)
    public String getDescription() {
        return this.description;
    }

    public TCustomerSay setDescription(String description) {
        this.description = description;
        return this;
    }

    @NotNull
    @Size(max = 500)
    public String getProducts() {
        return this.products;
    }

    public TCustomerSay setProducts(String products) {
        this.products = products;
        return this;
    }

    @NotNull
    @Size(max = 65535)
    public String getContent() {
        return this.content;
    }

    public TCustomerSay setContent(String content) {
        this.content = content;
        return this;
    }

    public Integer getOid() {
        return this.oid;
    }

    public TCustomerSay setOid(Integer oid) {
        this.oid = oid;
        return this;
    }

    @NotNull
    public Timestamp getCdate() {
        return this.cdate;
    }

    public TCustomerSay setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    @NotNull
    public Timestamp getMdate() {
        return this.mdate;
    }

    public TCustomerSay setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TCustomerSay (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(logo);
        sb.append(", ").append(description);
        sb.append(", ").append(products);
        sb.append(", ").append(content);
        sb.append(", ").append(oid);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
