/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 押金全付+用押金抵扣租金的方式的订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCutbillDepositOrder implements Serializable {

    private static final long serialVersionUID = -953158822;

    private Integer   id;
    private String    orderId;
    private Integer   productId;
    private Integer   customerId;
    private String    title;
    private Byte      rentType;
    private Byte      status;
    private Timestamp cdate;
    private Timestamp mdate;

    public TCutbillDepositOrder() {}

    public TCutbillDepositOrder(TCutbillDepositOrder value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.productId = value.productId;
        this.customerId = value.customerId;
        this.title = value.title;
        this.rentType = value.rentType;
        this.status = value.status;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TCutbillDepositOrder(
        Integer   id,
        String    orderId,
        Integer   productId,
        Integer   customerId,
        String    title,
        Byte      rentType,
        Byte      status,
        Timestamp cdate,
        Timestamp mdate
    ) {
        this.id = id;
        this.orderId = orderId;
        this.productId = productId;
        this.customerId = customerId;
        this.title = title;
        this.rentType = rentType;
        this.status = status;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    public Integer getId() {
        return this.id;
    }

    public TCutbillDepositOrder setId(Integer id) {
        this.id = id;
        return this;
    }

    @Size(max = 30)
    public String getOrderId() {
        return this.orderId;
    }

    public TCutbillDepositOrder setOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public TCutbillDepositOrder setProductId(Integer productId) {
        this.productId = productId;
        return this;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public TCutbillDepositOrder setCustomerId(Integer customerId) {
        this.customerId = customerId;
        return this;
    }

    @Size(max = 300)
    public String getTitle() {
        return this.title;
    }

    public TCutbillDepositOrder setTitle(String title) {
        this.title = title;
        return this;
    }

    public Byte getRentType() {
        return this.rentType;
    }

    public TCutbillDepositOrder setRentType(Byte rentType) {
        this.rentType = rentType;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TCutbillDepositOrder setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @NotNull
    public Timestamp getCdate() {
        return this.cdate;
    }

    public TCutbillDepositOrder setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    public Timestamp getMdate() {
        return this.mdate;
    }

    public TCutbillDepositOrder setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TCutbillDepositOrder (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(productId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(title);
        sb.append(", ").append(rentType);
        sb.append(", ").append(status);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
