/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGroups implements Serializable {

    private static final long serialVersionUID = -266229759;

    private Integer   id;
    private String    name;
    private Byte      category;
    private Integer   parent;
    private Byte      status;
    private String    remark;
    private Boolean   visiable;
    private Timestamp cdate;
    private Timestamp mdate;

    public TGroups() {}

    public TGroups(TGroups value) {
        this.id = value.id;
        this.name = value.name;
        this.category = value.category;
        this.parent = value.parent;
        this.status = value.status;
        this.remark = value.remark;
        this.visiable = value.visiable;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TGroups(
        Integer   id,
        String    name,
        Byte      category,
        Integer   parent,
        Byte      status,
        String    remark,
        Boolean   visiable,
        Timestamp cdate,
        Timestamp mdate
    ) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.parent = parent;
        this.status = status;
        this.remark = remark;
        this.visiable = visiable;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    public Integer getId() {
        return this.id;
    }

    public TGroups setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 300)
    public String getName() {
        return this.name;
    }

    public TGroups setName(String name) {
        this.name = name;
        return this;
    }

    public Byte getCategory() {
        return this.category;
    }

    public TGroups setCategory(Byte category) {
        this.category = category;
        return this;
    }

    public Integer getParent() {
        return this.parent;
    }

    public TGroups setParent(Integer parent) {
        this.parent = parent;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TGroups setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Size(max = 100)
    public String getRemark() {
        return this.remark;
    }

    public TGroups setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    public Boolean getVisiable() {
        return this.visiable;
    }

    public TGroups setVisiable(Boolean visiable) {
        this.visiable = visiable;
        return this;
    }

    public Timestamp getCdate() {
        return this.cdate;
    }

    public TGroups setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    public Timestamp getMdate() {
        return this.mdate;
    }

    public TGroups setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TGroups (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(category);
        sb.append(", ").append(parent);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);
        sb.append(", ").append(visiable);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
