/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderPayEvent implements Serializable {

    private static final long serialVersionUID = -948696556;

    private Long      id;
    private Integer   customerId;
    private String    orderId;
    private Integer   balanceDate;
    private Byte      status;
    private Byte      typeId;
    private Byte      syncStatus;
    private Timestamp cdate;
    private Timestamp mdate;

    public TOrderPayEvent() {}

    public TOrderPayEvent(TOrderPayEvent value) {
        this.id = value.id;
        this.customerId = value.customerId;
        this.orderId = value.orderId;
        this.balanceDate = value.balanceDate;
        this.status = value.status;
        this.typeId = value.typeId;
        this.syncStatus = value.syncStatus;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TOrderPayEvent(
        Long      id,
        Integer   customerId,
        String    orderId,
        Integer   balanceDate,
        Byte      status,
        Byte      typeId,
        Byte      syncStatus,
        Timestamp cdate,
        Timestamp mdate
    ) {
        this.id = id;
        this.customerId = customerId;
        this.orderId = orderId;
        this.balanceDate = balanceDate;
        this.status = status;
        this.typeId = typeId;
        this.syncStatus = syncStatus;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    public Long getId() {
        return this.id;
    }

    public TOrderPayEvent setId(Long id) {
        this.id = id;
        return this;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public TOrderPayEvent setCustomerId(Integer customerId) {
        this.customerId = customerId;
        return this;
    }

    @NotNull
    @Size(max = 20)
    public String getOrderId() {
        return this.orderId;
    }

    public TOrderPayEvent setOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    @NotNull
    public Integer getBalanceDate() {
        return this.balanceDate;
    }

    public TOrderPayEvent setBalanceDate(Integer balanceDate) {
        this.balanceDate = balanceDate;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TOrderPayEvent setStatus(Byte status) {
        this.status = status;
        return this;
    }

    public Byte getTypeId() {
        return this.typeId;
    }

    public TOrderPayEvent setTypeId(Byte typeId) {
        this.typeId = typeId;
        return this;
    }

    public Byte getSyncStatus() {
        return this.syncStatus;
    }

    public TOrderPayEvent setSyncStatus(Byte syncStatus) {
        this.syncStatus = syncStatus;
        return this;
    }

    @NotNull
    public Timestamp getCdate() {
        return this.cdate;
    }

    public TOrderPayEvent setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    @NotNull
    public Timestamp getMdate() {
        return this.mdate;
    }

    public TOrderPayEvent setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOrderPayEvent (");

        sb.append(id);
        sb.append(", ").append(customerId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(balanceDate);
        sb.append(", ").append(status);
        sb.append(", ").append(typeId);
        sb.append(", ").append(syncStatus);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
