/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.db_mall.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderBalance implements Serializable {

    private static final long serialVersionUID = 1150235450;

    private String     orderId;
    private Byte       payStatus;
    private BigDecimal deposit;
    private BigDecimal creditDeposit;
    private BigDecimal payDeposit;
    private Byte       depositType;
    private Integer    couponId;
    private BigDecimal couponAmount;
    private BigDecimal insuranceAmount;
    private BigDecimal addedServiceAmount;
    private BigDecimal payedAmount;
    private BigDecimal eCurrencyVirtual;
    private BigDecimal saleAmount;
    private BigDecimal rent;
    private BigDecimal needAmount;
    private Timestamp  useCouponDate;
    private Timestamp  cdate;
    private Timestamp  mdate;

    public TOrderBalance() {}

    public TOrderBalance(TOrderBalance value) {
        this.orderId = value.orderId;
        this.payStatus = value.payStatus;
        this.deposit = value.deposit;
        this.creditDeposit = value.creditDeposit;
        this.payDeposit = value.payDeposit;
        this.depositType = value.depositType;
        this.couponId = value.couponId;
        this.couponAmount = value.couponAmount;
        this.insuranceAmount = value.insuranceAmount;
        this.addedServiceAmount = value.addedServiceAmount;
        this.payedAmount = value.payedAmount;
        this.eCurrencyVirtual = value.eCurrencyVirtual;
        this.saleAmount = value.saleAmount;
        this.rent = value.rent;
        this.needAmount = value.needAmount;
        this.useCouponDate = value.useCouponDate;
        this.cdate = value.cdate;
        this.mdate = value.mdate;
    }

    public TOrderBalance(
        String     orderId,
        Byte       payStatus,
        BigDecimal deposit,
        BigDecimal creditDeposit,
        BigDecimal payDeposit,
        Byte       depositType,
        Integer    couponId,
        BigDecimal couponAmount,
        BigDecimal insuranceAmount,
        BigDecimal addedServiceAmount,
        BigDecimal payedAmount,
        BigDecimal eCurrencyVirtual,
        BigDecimal saleAmount,
        BigDecimal rent,
        BigDecimal needAmount,
        Timestamp  useCouponDate,
        Timestamp  cdate,
        Timestamp  mdate
    ) {
        this.orderId = orderId;
        this.payStatus = payStatus;
        this.deposit = deposit;
        this.creditDeposit = creditDeposit;
        this.payDeposit = payDeposit;
        this.depositType = depositType;
        this.couponId = couponId;
        this.couponAmount = couponAmount;
        this.insuranceAmount = insuranceAmount;
        this.addedServiceAmount = addedServiceAmount;
        this.payedAmount = payedAmount;
        this.eCurrencyVirtual = eCurrencyVirtual;
        this.saleAmount = saleAmount;
        this.rent = rent;
        this.needAmount = needAmount;
        this.useCouponDate = useCouponDate;
        this.cdate = cdate;
        this.mdate = mdate;
    }

    @NotNull
    @Size(max = 20)
    public String getOrderId() {
        return this.orderId;
    }

    public TOrderBalance setOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    public Byte getPayStatus() {
        return this.payStatus;
    }

    public TOrderBalance setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
        return this;
    }

    public BigDecimal getDeposit() {
        return this.deposit;
    }

    public TOrderBalance setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
        return this;
    }

    public BigDecimal getCreditDeposit() {
        return this.creditDeposit;
    }

    public TOrderBalance setCreditDeposit(BigDecimal creditDeposit) {
        this.creditDeposit = creditDeposit;
        return this;
    }

    public BigDecimal getPayDeposit() {
        return this.payDeposit;
    }

    public TOrderBalance setPayDeposit(BigDecimal payDeposit) {
        this.payDeposit = payDeposit;
        return this;
    }

    public Byte getDepositType() {
        return this.depositType;
    }

    public TOrderBalance setDepositType(Byte depositType) {
        this.depositType = depositType;
        return this;
    }

    public Integer getCouponId() {
        return this.couponId;
    }

    public TOrderBalance setCouponId(Integer couponId) {
        this.couponId = couponId;
        return this;
    }

    public BigDecimal getCouponAmount() {
        return this.couponAmount;
    }

    public TOrderBalance setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
        return this;
    }

    public BigDecimal getInsuranceAmount() {
        return this.insuranceAmount;
    }

    public TOrderBalance setInsuranceAmount(BigDecimal insuranceAmount) {
        this.insuranceAmount = insuranceAmount;
        return this;
    }

    public BigDecimal getAddedServiceAmount() {
        return this.addedServiceAmount;
    }

    public TOrderBalance setAddedServiceAmount(BigDecimal addedServiceAmount) {
        this.addedServiceAmount = addedServiceAmount;
        return this;
    }

    public BigDecimal getPayedAmount() {
        return this.payedAmount;
    }

    public TOrderBalance setPayedAmount(BigDecimal payedAmount) {
        this.payedAmount = payedAmount;
        return this;
    }

    public BigDecimal getECurrencyVirtual() {
        return this.eCurrencyVirtual;
    }

    public TOrderBalance setECurrencyVirtual(BigDecimal eCurrencyVirtual) {
        this.eCurrencyVirtual = eCurrencyVirtual;
        return this;
    }

    public BigDecimal getSaleAmount() {
        return this.saleAmount;
    }

    public TOrderBalance setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
        return this;
    }

    public BigDecimal getRent() {
        return this.rent;
    }

    public TOrderBalance setRent(BigDecimal rent) {
        this.rent = rent;
        return this;
    }

    public BigDecimal getNeedAmount() {
        return this.needAmount;
    }

    public TOrderBalance setNeedAmount(BigDecimal needAmount) {
        this.needAmount = needAmount;
        return this;
    }

    public Timestamp getUseCouponDate() {
        return this.useCouponDate;
    }

    public TOrderBalance setUseCouponDate(Timestamp useCouponDate) {
        this.useCouponDate = useCouponDate;
        return this;
    }

    @NotNull
    public Timestamp getCdate() {
        return this.cdate;
    }

    public TOrderBalance setCdate(Timestamp cdate) {
        this.cdate = cdate;
        return this;
    }

    @NotNull
    public Timestamp getMdate() {
        return this.mdate;
    }

    public TOrderBalance setMdate(Timestamp mdate) {
        this.mdate = mdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOrderBalance (");

        sb.append(orderId);
        sb.append(", ").append(payStatus);
        sb.append(", ").append(deposit);
        sb.append(", ").append(creditDeposit);
        sb.append(", ").append(payDeposit);
        sb.append(", ").append(depositType);
        sb.append(", ").append(couponId);
        sb.append(", ").append(couponAmount);
        sb.append(", ").append(insuranceAmount);
        sb.append(", ").append(addedServiceAmount);
        sb.append(", ").append(payedAmount);
        sb.append(", ").append(eCurrencyVirtual);
        sb.append(", ").append(saleAmount);
        sb.append(", ").append(rent);
        sb.append(", ").append(needAmount);
        sb.append(", ").append(useCouponDate);
        sb.append(", ").append(cdate);
        sb.append(", ").append(mdate);

        sb.append(")");
        return sb.toString();
    }
}
