/*
 * This file is generated by jOOQ.
 */
package cn.zyj.dbexporter.jooq.tables;


import cn.zyj.dbexporter.jooq.DbMall;
import cn.zyj.dbexporter.jooq.Indexes;
import cn.zyj.dbexporter.jooq.Keys;
import cn.zyj.dbexporter.jooq.tables.records.TMenuRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMenu extends TableImpl<TMenuRecord> {

    private static final long serialVersionUID = 859091156;

    /**
     * The reference instance of <code>db_mall.t_menu</code>
     */
    public static final TMenu T_MENU = new TMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMenuRecord> getRecordType() {
        return TMenuRecord.class;
    }

    /**
     * The column <code>db_mall.t_menu.id</code>. 菜单标识
     */
    public final TableField<TMenuRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "菜单标识");

    /**
     * The column <code>db_mall.t_menu.parent_id</code>. 父菜单标识
     */
    public final TableField<TMenuRecord, Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT, this, "父菜单标识");

    /**
     * The column <code>db_mall.t_menu.status</code>. 菜单状态(0:隐藏;1:显示)
     */
    public final TableField<TMenuRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "菜单状态(0:隐藏;1:显示)");

    /**
     * The column <code>db_mall.t_menu.name</code>. 菜单名称
     */
    public final TableField<TMenuRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "菜单名称");

    /**
     * The column <code>db_mall.t_menu.sno</code>. 菜单序号
     */
    public final TableField<TMenuRecord, Long> SNO = createField("sno", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "菜单序号");

    /**
     * The column <code>db_mall.t_menu.href</code>. 菜单链接
     */
    public final TableField<TMenuRecord, String> HREF = createField("href", org.jooq.impl.SQLDataType.VARCHAR(100), this, "菜单链接");

    /**
     * The column <code>db_mall.t_menu.description</code>. 菜单描述
     */
    public final TableField<TMenuRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255), this, "菜单描述");

    /**
     * Create a <code>db_mall.t_menu</code> table reference
     */
    public TMenu() {
        this(DSL.name("t_menu"), null);
    }

    /**
     * Create an aliased <code>db_mall.t_menu</code> table reference
     */
    public TMenu(String alias) {
        this(DSL.name(alias), T_MENU);
    }

    /**
     * Create an aliased <code>db_mall.t_menu</code> table reference
     */
    public TMenu(Name alias) {
        this(alias, T_MENU);
    }

    private TMenu(Name alias, Table<TMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMenu(Name alias, Table<TMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("菜单表"));
    }

    public <O extends Record> TMenu(Table<O> child, ForeignKey<O, TMenuRecord> key) {
        super(child, key, T_MENU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMall.DB_MALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_MENU_FK_MENU_PARENT_ID, Indexes.T_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<TMenuRecord>>asList(Keys.KEY_T_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TMenuRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TMenuRecord, ?>>asList(Keys.T_MENU_IBFK_1);
    }

    public cn.zyj.dbexporter.jooq.tables.TMenu tMenu() {
        return new cn.zyj.dbexporter.jooq.tables.TMenu(this, Keys.T_MENU_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMenu as(String alias) {
        return new TMenu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMenu as(Name alias) {
        return new TMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMenu rename(String name) {
        return new TMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMenu rename(Name name) {
        return new TMenu(name, null);
    }
}
